### ISSUE TITLE
How to load multiple reward videos or interstitials

### ISSUE THREAD

**Issue by omar-bz** [kloder-games/godot-admob#101]
Hi,
so this is a question more then it is an issue
I am targeting android using godot 3.2
As i want to use different rewarded videos for different parts of my app, I created different scripts for each video rewarded, but apparently this can't work since the admob is a singleton, and when I initialize the banner, interstitials and reward videos the callbacks fire inside the last script and therefor always the last reward video is showed and that seems logical to me.
So what should I do in order to load multiple reward videos(or interstitials), load them in advance and show them in the right moment?

**Comment by Shin-NiL** [comment]
As you stated, the Godot modules are a singleton, so you can't.

**Comment by omar-bz** [comment]
so I must use only one video rewarded and one interstitial in order for it to work?

**Comment by Shin-NiL** [comment]
Indeed, the idea is show an ad, reload, when ready, show again.

**Comment by omar-bz** [comment]
ok, thanks
