### ISSUE TITLE
is it possible to upload Google Mobile Ads SDK (<= 7.41.0)

### ISSUE THREAD

**Issue by mani144** [kloder-games/godot-admob#105]
Greetings,

I tried to download 7.41.0 version but it seems google removed it from its website.
is it possible to give us link for it or if you have a way to download it can u share it?

Thank you

**Comment by fogine** [comment]
Use cocoapods
https://cocoapods.org/

**Comment by mani144** [comment]
its not that easy, i tried multiple times , and so far i could not do anything

**Comment by mani144** [comment]
Done :) , it seems you must use xcodeworkspace not the usual .xcode
