### ISSUE TITLE
Banner problem HELP!

### ISSUE THREAD

**Issue by buxnast** [kloder-games/godot-admob#115]
I have trouble setting height of my banner and at the moment I don't know how to do so,
Default banner is 320x100 covering too much content, I want to set height to 50, how do I do that?
If anyone can explain I would appreciate it very much also i have tried using getBannerHeight() but it seems i'm doing it wrong. Thanks in common!

**Comment by Shin-NiL** [comment]
This module uses [Smart Banner](https://developers.google.com/admob/android/banner/smart), so it's not possible to set its width or height by yourself.

**Comment by buxnast** [comment]
Alright, thanks for letting me know! This module helps me a lot even without banners, thanks a lot man, all best!
