### ISSUE TITLE
Ads for all platforms?

### ISSUE THREAD

**Issue by japalekhin** [kloder-games/godot-admob#116]
Not an issue, more like a question.

Let's say, hypothetically, that I built an awesome game and will release it to all platforms supported by Godot.

Would admob (using this) work on android, ios, widows, linux, mac, web?

**Comment by Shin-NiL** [comment]
This module only supports Android and iOS.

**Comment by gustavottc** [comment]
Hi @japalekhin , Admob only supports Android and iOS, isnt possible to do the module to the others platforms, thanks

**Comment by japalekhin** [comment]
makes sense. thanks for the time.
