### ISSUE TITLE
Preloading 

### ISSUE THREAD

**Issue by kjav** [kloder-games/godot-admob#120]
**OS target (Android/iOS):** Android

**Godot version:** 3.1.1-stable

**Issue description:**

Hi, currently the "playRewardedVideo" function takes no arguments, and plays the one loaded reward video. However, the "loadRewardedVideo" function takes a string advert id argument.

I like to preload adverts so that the user doesn't have to wait. This only has to happen once per advert per playthrough, so the data usage isn't too high.

However this doesn't work with multiple reward video units. You have to use just one reward video for every place in your game. The disadvantage of this is that you can't tell where the player has clicked it, so you can't tell which reward video buttons are used more often than others.

I propose that instead of storing just one reward video, a dictionary is built which allows the user to load multiple ad id's at once, and play them separately.

**Comment by Shin-NiL** [comment]
The rewarded video is a _singleton_ on Google SDK, so I don't think this is possible.

**Comment by kjav** [comment]
Oh, that's a shame! Thanks for reading this anyway. Feel free to close this
issue.
