### ISSUE TITLE
[ERROR]: AttributeError: 'SConsEnvironment' object has no attribute 'android_add_dependency':

### ISSUE THREAD

**Issue by gustavottc** [kloder-games/godot-admob#121]
**OS target (Android/iOS):**
Android

**Godot version:**
3.2.1

**Issue description:**
When i try to compile to Android, give me this error:

![image](https://user-images.githubusercontent.com/20030153/77839375-6d1b8b00-7152-11ea-9c19-fff97c5eba80.png)

**Comment by Shin-NiL** [comment]
As described in the readme file, this kind of module is not supported anymore on Godot 3.2+. You must use the new plugin system, [here's the port of this admob module](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/) to this new system.

**Comment by gustavottc** [comment]
> As described in the readme file, this kind of module is not supported anymore on Godot 3.2+. You must use the new plugin system, [here's the port of this admob module](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/) to this new system.

ty, i didnt saw
