### ISSUE TITLE
GDPR Question

### ISSUE THREAD

**Issue by kjav** [kloder-games/godot-admob#122]
Hi,

Does this module use personalised ads? If so, is there an option to turn this off to comply with GDPR regulation in Europe?

Thanks!

**Comment by Shin-NiL** [comment]
No, this module doesn't have this option. The [new android plugin](https://godotengine.org/article/godot-3-2-will-get-new-android-plugin-system) does.

**Comment by kjav** [comment]
I hadn't seen that - I'll update my project to Godot 3.2.1 then. Thanks for the help!

**Comment by kjav** [comment]
For future travelers - here is a link to Shin-NiL's new admob add-on (for Godot 3.2 and higher)!
https://github.com/Shin-NiL/Godot-Android-Admob-Plugin
