### ISSUE TITLE
[BUG] 3.2.1 Crashes on initialize AdmobInterstitial

### ISSUE THREAD

**Issue by gustavottc** [kloder-games/godot-admob#126]
**OS target (Android/iOS):** iOS

**Godot version:** 3.2.1

**Issue description:**
![image](https://user-images.githubusercontent.com/20030153/79774117-c23d5d80-8308-11ea-83bb-30e56af12eae.png)

I downloaded the compiled from:

https://github.com/GhostWalker562/godot-admob-iOS-precompiled/releases

**Comment by cemeai** [comment]
Getting exactly the same issue

**Comment by gustavottc** [comment]
Ty, in a few days i will try it and give a feedback

**Comment by gustavottc** [comment]
Did you encounter this error? 

https://github.com/kloder-games/godot-admob/issues/124

**Comment by cemeai** [comment]
haven't sorry

**Comment by Sajyd** [comment]
I'm having the same issue. Compiled iOS export template from 3.2.1-stable source and followed readme instruction still had this issue. Any idea what could be wrong ? I'm sure I initialized it well.

**Comment by Sajyd** [comment]
Finally managed to make it work by recompiling with old code

**Comment by gustavottc** [comment]
> Finally managed to make it work by recompiling with old code

@Sajyd can you please upload the file to i test?

**Comment by gustavottc** [comment]
Resolved on https://github.com/kloder-games/godot-admob/pull/128, thanks @minhanhhere
