### ISSUE TITLE
Rewarded Video don't open

### ISSUE THREAD

**Issue by gotognetti** [kloder-games/godot-admob#13]
Hi, I'm new in godot developement.
First, thanks for the library. Is very helpful.

I'm using godot in Linux.

I tried to implement it in my game using the godot 2.1.4 but when I run on Android, it just blink the godot screen and crashs.
So I downloaded godot 2.1 and adapt my game to export in the export template 2.1 and finally got it to work. 
Now my problem is, the banner and interstitial are working well, but the rewarded video don't open.
Even with the demo, that comes with the library the video don't open.

I am debuging it with adb logcat and get this response:

SCRIPT ERROR: _on_BtnRewardedVideo_pressed: Invalid call. Nonexistent function 'showRewardedVideo' in base 'JNISingleton'.

What am I doing wrong?

**Comment by jtaart** [comment]
I think the example is broken, because I was testing it on iOS and the reward videos didn't work until I made a button to reload the reward video. I think the example toggles the video button off after it fails to load the first time or something.

**Comment by mkamener** [comment]
I am also able to load the banner ads and interstitial ads with no problem, but get the following error when I try to load the rewarded ads:

2018-01-18 21:53:59.460806+1100 godot_opt.iphone[2833:341342] Reward based video ad failed to load: No ad returned from any ad server.
2018-01-18 21:53:59.463534+1100 godot_opt.iphone[2833:341629] <Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

I made a button to call the loadRewardedVideo() function as jtaart mentioned, but that didn't help. I've also added the linker flag which the error mentions.

I'm using Xcode 9.2 and have version 7.27.0 of the Google Mobile Ads SDK, and running the example on my iPhone

**Comment by mkamener** [comment]
So the issue that I was having was because I had "Limit Ad Tracking" enabled on my iPhone. Going into Settings -> Privacy -> Advertising and disabling Limit Ad Tracking allowed the rewarded ads to load.

In short the issue was purely on my end - however it does make me wonder how I could effectively implement rewarded ads when not all users would have this setting disabled
