### ISSUE TITLE
How to use API methods in iOS project

### ISSUE THREAD

**Issue by mattdamon108** [kloder-games/godot-admob#142]
**OS target (Android/iOS):**
iOS 13.4

**Godot version:**
3.2

**Issue description:**
I successfully compiled the godot source code with godot-admob module following the official documentation. I exported the project for iOS. But I'm wondering how can I use and call the API method in my godot project? For example, there is `loadBanner(id, isTop)` method. How can I call this method inside my godot project actually? I can't find any example project for it except android.

**Comment by gustavottc** [comment]
Hey, we already have a example for Android and iOS, both are working 

https://github.com/kloder-games/godot-admob/blob/master/examples/godot-3/main.gd

**Comment by mattdamon108** [comment]
Thx! I think I missed it
