### ISSUE TITLE
New Framework may be needed

### ISSUE THREAD

**Issue by dala00** [kloder-games/godot-admob#146]
**OS target (Android/iOS):**
iOS

**Godot version:**
3.2.2

**Issue description:**

Just information. Updating README may be needed.

When I used Google Mobile Ads SDK7.65.0, following error occurred.

```
ld: warning: Could not find or use auto-linked framework 'FBLPromises'
"_OBJC_CLASS_$_JSContext", referenced from:
```

After adding JavaScriptCore.framework, resolved.

https://community.clickteam.com/threads/107875-Could-not-find-or-use-auto-linked-framework-FBLPromises

**Comment by gustavottc** [comment]
Thanks for your collaboration, just need to include this framework and will works?

**Comment by dala00** [comment]
Errors difficult to solve was only that.

On 7.65.0, UserMessagingPlatform.framework also exists. I don't know if this should be included, but I'm now including. (I'm not trying without this yet)

**Comment by gustavottc** [comment]
Thanks, i will update the Readme, if theres something more to update please tell here
