### ISSUE TITLE
 Only test ads are showing

### ISSUE THREAD

**Issue by osimuka** [kloder-games/godot-admob#147]
**OS target: iOS**

**Godot version: 3.2.2**

**Issue description: Only test ads are showing even though `is_real` is set to `true`**
Interstitial ads only shows in test mode, this has stopped me from publishing the game to the appstore, is there a parameter setting in the source code that causes this to happen? I'm using godots ios debug *.a file.

**Comment by gustavottc** [comment]
hi @osimuka , did you solve?

**Comment by osimuka** [comment]
yes, just solved it. Thanks
The solution was I implemented it using Godot autoload 🚀
