### ISSUE TITLE
Video Tutorial for iOS Install and Setup

### ISSUE THREAD

**Issue by ACB-prgm** [kloder-games/godot-admob#153]
Hey Everybody,

For someone with rudimentary programming knowledge, figuring out how to install this module, recompile it for iOS, and configure the Xcode project was tough, so I made this video tutorial on getting it installed!

https://www.youtube.com/watch?v=s5sNrOM3Oeo

I figured I wasn't the only person in that boat, so I hope this helps some people! The video goes through how to install the module and recompile Godot to use it. It also goes through configuring the Xcode project file and an example using the module in code.

Please leave the video a like and leave a comment if you can!

**Comment by gustavottc** [comment]
Can I put this on readme? Very cool

**Comment by ACB-prgm** [comment]
@gustavottc Absolutely!
