### ISSUE TITLE
Can't use Admob Plugin for iOS in Godot

### ISSUE THREAD

**Issue by johannesjaeger123** [kloder-games/godot-admob#154]
OS target (Android/iOS): 
iOS

Godot version: 
3.2.3 (stable)

Issue description:
I downloaded Godot source, dropped the admob directory provided by kloder-games in the modules directory of Godot source. Then I downloaded GoogleMobileAdsSDKiOS 7.67.0 and dropped in the iOS/lib folder. Next I compiled the modified Godot source for macOS since I'm using a Mac with macOS 10.15.7. After compiling successfully the file in the bin/ subdirectory was not executable until I changed it's format by replacing the ending with .app. Afterwards I could open Godot and it was working normally, but I couldn't find the Admob Plugin nor did it's functions work.
I didn't recompile the iOS export template yet, because I don't know how. I can only find the normal export template from Godot which I used before, but I can't compile it for iOS. 
Does anyone know how the recompiling of the iOS export template works and with which source? 
Could this be the issue why I can't find the Admob Plugin in Godot?

**Comment by gustavottc** [comment]
hi @johannesjaeger123 , did you solve it?

**Comment by ghost** [comment]
Yes, thanks to the video tutorial by @ACB-prgm. I was not aware that I need to export my project with the unmodified version of Godot.
