### ISSUE TITLE
Crash on Android when use GodotPaymentV3 and GodotAdMob together

### ISSUE THREAD

**Issue by sanja-sa** [kloder-games/godot-admob#17]
Godot 2.1
If I use only one module Payment or AdMob it's work fine, but together it's crashed app.
![admob_err](https://user-images.githubusercontent.com/6029207/37510111-b72ed55c-2902-11e8-9544-a686daa29feb.png)
In other order:
![admob_err](https://user-images.githubusercontent.com/6029207/37510651-92b9d0a8-2904-11e8-9a78-f9279143d3f2.png)

**Comment by Shin-NiL** [comment]
Could you please paste your `[android]` section in `engine.cfg`? It should be separated by commas, something like this:

```
[android]
modules="org/godotengine/godot/GodotPaymentV3,org/godotengine/godot/GodotAdMob"
```

**Comment by sanja-sa** [comment]
[android]

modules="org/godotengine/godot/GodotPaymentV3, org/godotengine/godot/GodotAdMobV3"

**Comment by Shin-NiL** [comment]
Try removing the empty space.

**Comment by sanja-sa** [comment]
@Shin-NiL  Thank you, it's really casual bug :)
