### ISSUE TITLE
Trying out for godot 3.0.2

### ISSUE THREAD

**Issue by houfaru** [kloder-games/godot-admob#18]
Hi,
I'm interested in using this module
I tried this for Godot 3.0.2, but Engine.has_instance("AdMob") always returns false

I'm kind of new to Godot, so I would expect that my problem would be with the way i set it up.

I previously asked here: https://github.com/godotengine/godot/issues/17521
but after i fixed it, it is still not working

Here are the steps:

1. download
https://github.com/kloder-games/godot-admob/tree/master/admob into admob folder
https://github.com/godotengine/godot into ~/godot-3.0.2-stable
put admob folder to ~/godot-3.0.2-stable/modules

2. execute the following commands
cd ~/godot-3.0.2-stable

scons platform=x11

scons platform=android target=release -j 4
cd platform/android/java
./gradlew build
cd ../../..

scons platform=android target=release_debug -j 4
cd platform/android/java
./gradlew build
cd ../../..

3. execute godot.x11.tools.64
create a new project and new main scene with its script
Add the following to project.godot
[android]
modules="org/godotengine/godot/GodotAdMob"

4. Select Project->Export->Android->Options
add android_debug.apk and android_release.apk into Custom Package
Enable permissions: Access Network State, Internet
add Engine.has_instance("AdMob") into one the script you have
and It returns false(expected true)

Thanks

**Comment by Shin-NiL** [comment]
You don't need to compile the engine for X11, you can use the official builds. Everything looks fine except that.

To make sure all your changes on `project.godot` was saved, close Godot, edit project.godot, save the file, then open Godot.

Could you test our [example project](https://github.com/kloder-games/godot-admob/tree/master/examples/godot-3)?

**Comment by houfaru** [comment]
Hi,
sorry, I didn't know that it won't work when you test it with F6.
Apparently I should export the afk first then test it on phone/emulator.

I tested your example project with three test ad units(banner interstitial, and rewarded video):
https://developers.google.com/admob/android/test-ads#sample_ad_units
and It's works fine

thanks

**Comment by Shin-NiL** [comment]
Yeah, it'll only work on the real device or Android emulator.
