### ISSUE TITLE
can't compile the templates

### ISSUE THREAD

**Issue by marcusViniciusMP** [kloder-games/godot-admob#21]
scons platform=android target=release
scons: Reading SConscript files ...
Godot Android!!!!! (armv7) (with neon)
scons: done reading SConscript files.
scons: Building targets ...
[  4%] Compiling shared ==> platform/android/os_android.cpp
sh: 1: /home/marcus/android-ndk-r13b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++: not found
scons: *** [platform/android/os_android.os] Error 127
scons: building terminated because of errors.

i follow the steps, thats what i got

**Comment by Shin-NiL** [comment]
Are you able to compile the template without the Admob module?

**Comment by marcusViniciusMP** [comment]
forget ir was my mistake sorry, wrong paths ate set system paths
