### ISSUE TITLE
if Globals.has_singleton("bbAdmob") returns false

### ISSUE THREAD

**Issue by marcusViniciusMP** [kloder-games/godot-admob#22]
im using the 2.1.4 godot for linux 64, i did all the steps but its fails... i have compiled the godot and also the export templates, had configured all as was described here, just returns false.
what should i do ? i could follow all the steps, recompiled godot, also the export templates but nothing happens now. ot just retorns false for Globals.has_singleton("bbAdmob"). 
.
var admob = null;
var admob_banner_id = "ca-app-pub-4271047361119801/6475071680" # your banner id here

func _ready():
	if Globals.has_singleton("bbAdmob"): <- returns false !
		admob = Globals.get_singleton("bbAdmob")
		admob.init(true, get_instance_ID())
		admob.loadBanner(admob_banner_id, true)
		print("largura = "+str(getBannerWidith()))
		print("altura = "+str(getBannerHeight()))
		
	else : dbg.set_text("nao funcionou")

**Comment by Shin-NiL** [comment]
Please, check the [example code](https://github.com/kloder-games/godot-admob/tree/master/examples/godot-2).

One thing I can note is that this module name is `AdMob `and not `bbAdmob`.

**Comment by marcusViniciusMP** [comment]
i fix that but now when i execute the example, o got this error from adb logcat:
ERROR: _initialize_java_modules: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob
I/godot   (29727):    At: platform/android/java_glue.cpp:968.

**Comment by marcusViniciusMP** [comment]
ERROR: create: Condition ' !create_func ' is true. returned: 0
I/godot   ( 4708):    At: core/os/mutex.cpp:38.

**Comment by Shin-NiL** [comment]
Please double check all steps described in the [README file](https://github.com/kloder-games/godot-admob/blob/master/README.md), if you skip one of them you'll probably get this error.

It's very hard to us to know exactly what's happening in this case.

**Comment by homarox** [comment]
I have the same problem too in Godot 3.0.6

> 08-23 11:57:00.922 15728 15770 I godot   : Loading module: org/godotengine/godot/GodotAdMob
> 08-23 11:57:00.922 15728 15770 E godot   : **ERROR**: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob
> 08-23 11:57:00.922 15728 15770 E godot   :    At: platform/android/java_glue.cpp:861:_initialize_java_modules() - Condition ' !singletonClass ' is true. Continuing..:
