### ISSUE TITLE
AdMob: onAdFailedToLoad -> ERROR_CODE_INTERNAL_ERROR

### ISSUE THREAD

**Issue by FosterProject** [kloder-games/godot-admob#24]
I don't know what I'm doing wrong here.

I'm trying to get a banner ad to show display. I've signed up with AdMob and created an Ad Unit and have my ID. I'm using that ID as per the examples in the repo for Godot 3 and I'm getting this error every single time.

It seems that the `admob.loadBanner(ad_banner_ID, display_top)` call doesn't throw any errors, but when I call `admob.showBanner()` it throws the title error.

Can anyone point me in the direction of some good resources or help me out directly?

Thanks

EDIT:

Does this have something to do with my AdMob App ID? That's not being passed to the `initialize` function, but an Android Activity is. I'm not too sure how the inners work for this module, but shouldn't I have to pass this ID along to initialize my AdMob to display banners etc?

EDIT #2:

I'm using the sample ad ID's provided here: https://developers.google.com/admob/android/test-ads

EDIT #3:

I believe I found the source of the error by doing a `adb logcat -s Ads`:
 ```
Starting ad request.
03-29 17:17:05.145 28109 28109 I Ads     : This request is sent from a test device.
03-29 17:17:05.502 28109 28446 W Ads     : Google Play Service is out of date, the Google Mobile Ads SDK will not integrate with Firebase. Admob/Firebase integration requires updated Google Play Service.
03-29 17:17:15.709 28109 28465 E Ads     : Error waiting for future.
```

Is this something I have to update on my end?

**Comment by FosterProject** [comment]
It turns out my test device was absurdly out of date and had several software versions to implement.

After doing these updates, the ad request was accepted and I was able to display banners correctly.

The module is working perfectly, this was all on my end.

----
Is there a better place to post my questions about this module rather than here? i.e. a Slack/Discord/IRC ? Or would you rather all issues be documented here for future reference?

**Comment by Shin-NiL** [comment]
I don't know about the others developers, but this is the main communication channel to me.
