### ISSUE TITLE
Request: Support for GDNative (Godot 3.0)

### ISSUE THREAD

**Issue by Corruptinator** [kloder-games/godot-admob#26]
Hello! Not sure if this is a longshot but is it possible to create a GDNative script of this module by any chance?

**Comment by Shin-NiL** [comment]
I'm not sure, but AFAIK we can't use Java (Android) code with GDNative, so all the module should be rewriten using C/C++ api for Admob.

**Comment by Corruptinator** [comment]
Understood.
