### ISSUE TITLE
Add this module to AssetLib

### ISSUE THREAD

**Issue by Heryhelder** [kloder-games/godot-admob#30]
Can you put this module in AssetLib? This way it will be easier for new developers to use the module to export their games.

**Comment by Shin-NiL** [comment]
This kind of module was not meant to be distributed on assetlib, even the distribuition of the pre compiled versions has its use very limited. 

Think in a very common scenario where you need Admob, share image and a Google Play Services modules. The pre compiled version will not help, as the user will need to recompile your custom template with all these modules inside.

**Comment by Shin-NiL** [comment]
Unfortunately it can't be done.
