### ISSUE TITLE
left click doesnt work as touch input

### ISSUE THREAD

**Issue by Tovaaa** [kloder-games/godot-admob#34]
**OS target (Android/iOS):** Android

**Godot version:** 3.0.2

**Issue description:**
i compiled export templates so that i could use admob ads in my project, but when i exported my game using those export templates the touch didnt work (it works fine on scenes where i dont use `if Input.is_action_just_pressed("ui_left_click"): ......`
if i run the project in editor everything works fine too, and if i export without those export templates it also works fine, so the problem must be export templates

**Comment by Shin-NiL** [comment]
Does it work if you compile the template without admob?

**Comment by Shin-NiL** [comment]
I think that the mouse actions doesn't work on mobile, you should use touches instead.

**Comment by Tovaaa** [comment]
they work, before i compiled my own export templates it worked fine, could you possibly compile debug template with admob and send it to me?

**Comment by Shin-NiL** [comment]
Surprisingly it works, indeed. I've tested with the official templates and my custom one with Admob, worked with all of them.

I don't have a debug version compiled, just release. But you can use it for testing.


[android_release.apk.zip](https://github.com/kloder-games/godot-admob/files/1987552/android_release.apk.zip)

**Comment by Tovaaa** [comment]
thanks, touch works with your apk :) but now my ads are not showing up for some reason :/ but it's most likely my fault, probably messed something up in the code while trying to get touch to work..

**Comment by Shin-NiL** [comment]
Nice, `adb logcat -s godot` can help you to debug your error.

**Comment by Tovaaa** [comment]
well i didnt do anything but when i tried it today again everything seems to work fine :P 

btw. what does this mean? `**ERROR**: Condition ' !obj ' is true.
05-10 15:14:32.147 23044 23044 E godot   :    At: platform/android/java_glue.cpp:1571:Java_org_godotengine_godot_GodotLib_calldeferred() - Condition ' !obj ' is true.`
