### ISSUE TITLE
Banner ad won't show (onAdFailedToLoad -> ERROR_CODE_INTERNAL_ERROR)

### ISSUE THREAD

**Issue by henriquelalves** [kloder-games/godot-admob#37]
**OS target (Android/iOS):**
Android

**Godot version:**
Godot v3.0

**Issue description:**
I created the AdMob account page for an App I still haven't created a page on PlayStore, and set up the module according to the instructions - but I can't seem to use the banner_id from AdMob. I always receive the error `onAdFailedToLoad -> ERROR_CODE_INTERNAL_ERROR` when trying the method show_banner(); but when I changed the banner_id to the ID of one of my apps already published on PlayStore, the method works just fine.

My intention was to test the banner before publishing the app, but do I have to publish it on playstore and link it to my AdMob account for the module to work?

**Comment by Shin-NiL** [comment]
>My intention was to test the banner before publishing the app, but do I have to publish it on playstore and link it to my AdMob account for the module to work?

No, it's not necessary. What I can tell you (by my own experience) is that Admob take some time to create and activate a new Ad, so if you try again after some hours it should work.

**Comment by henriquelalves** [comment]
That was exactly the problem! Just took some time and now the ad is working. Thanks!
