### ISSUE TITLE
couldn't find "libgodot_android.so"

### ISSUE THREAD

**Issue by snakeskinsalamander** [kloder-games/godot-admob#38]
**OS target (Android/iOS):**
Android

**Godot version:**
3.0.5

**Issue description:**
I'm sure I'm doing something wrong but I just can't figure out what it is. I have made an export template with admob included on the module folder. I was able to compile it (I am adding arm64v8 since I am targetting that architecture) and I was able to use it as an export.. For some reason, my app just start flickering on the godos splash screen when I'm starting. On logcat, I am getting the following

[DexPathList[[zip file "/data/app/org.syvernlab.myapp-_AzHS86tcW2TlX1XIlygGw==/base.apk"],nativeLibraryDirectories=[/data/app/org.syvernlab.myapp-_AzHS86tcW2TlX1XIlygGw==/lib/arm64, /data/app/org.syvernlab.myapp-_AzHS86tcW2TlX1XIlygGw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libgodot_android.so"

I'm wondering why it was unable to find it. I verified it is there on my source code. Do you have any suggestions on how to fix this?

**Comment by Shin-NiL** [comment]
Are you able to compile and run the template without the Admob module? It seems like it's an issue with the arm64 build.

**Comment by salomander86** [comment]
http://prntscr.com/ld4tvg
And release template is much lighter than debug, is it ok?

**Comment by salomander86** [comment]
I go this by recompiling godot... It just gone

**Comment by Shin-NiL** [comment]
So it worked now @salomander86? The release and debug templates should be almost the same size.

**Comment by elilan** [comment]
I have this problem too. And I compiled Godot 3.0.6 for android _without_ the **godot-admob** module. I used a clean version of godot source code. So... we can infer that it is not a problem with the module.

**Comment by salomander86** [comment]
Yeah, got it. I assume that the problem in gradle, ndk and buildToolsVersion versions. I played with versions and the problem just gone.

**Comment by salomander86** [comment]
my latest build.gradle file:

```
buildscript {
	repositories {
		mavenCentral()
        google()
        jcenter()
		
	}
	dependencies {
		classpath 'com.android.tools.build:gradle:3.2.1'
		
	}
}

apply plugin: 'com.android.application'

allprojects {
    repositories {
    jcenter()
	mavenCentral()
	google()
	
    }
}

dependencies {
	implementation 'com.android.support:appcompat-v7:27.1.1'  // can be removed if minSdkVersion 16 and modify DownloadNotification.java & V14CustomNotification.java
	implementation 'com.google.android.gms:play-services-ads:+'
	implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
	
}

android {

	lintOptions {
		abortOnError false
		disable 'MissingTranslation'
	}

	compileSdkVersion 27
	buildToolsVersion "28.0.3"
	useLibrary 'org.apache.http.legacy'

	packagingOptions {
		exclude 'META-INF/LICENSE'
		exclude 'META-INF/NOTICE'
	}
	defaultConfig {
		minSdkVersion 23
		targetSdkVersion 28
		
	}
	// Both signing and zip-aligning will be done at export time
	buildTypes.all { buildType ->
		buildType.zipAlignEnabled false
		buildType.signingConfig null
	}
	sourceSets {
		main {
			manifest.srcFile 'AndroidManifest.xml'
			java.srcDirs = ['src'
				,'/Users/stastkach/Documents/godot-3.0.6-stable/modules/admob/android'
			]
			res.srcDirs = [
				'res'
				
			]
			aidl.srcDirs = [
				'aidl'
				
			]
			assets.srcDirs = [
				'assets'
				
			]
		}
		debug.jniLibs.srcDirs = [
			'libs/debug'
			
		]
		release.jniLibs.srcDirs = [
			'libs/release'
			
		]
	}
		applicationVariants.all { variant ->
		variant.outputs.all { output ->
			output.outputFileName = "../../../../../../../bin/android_${variant.name}.apk"
		}
	}
}
```

**Comment by Javasamurai** [comment]
Any solution for this issue as happening with us too.

**Comment by Javasamurai** [comment]
As suggested by @salomander86. android-ndk-r15c works well with release build.

**Comment by Lucky0710** [comment]
Hi ! Sorry for coming back on this issue but i have EXACTLY the same problem as Salomander86, and i try hard to make it work since 5 days but i can't... 
So, i was wondering if you remeber the exact config you used last time you succeded building the release.apk and debug.apk, and what were the versions of you NDK, SDK, JDK etc...
This would help me a lot !
By the way i'm on windows 10, using godot 3.0.6
Thanks in advance !

**Comment by wombatwingdings** [comment]
I've had issues in the past where libgodot_android.so debug or release coming out with very small size. It seemed to be a problem with gradle. Killing gradle demon/restarting the machine and a clean build fixed it for me.

**Comment by Lucky0710** [comment]
Thank you very much ! I will try this today.
By the way, witch NDK version were you using ?
