### ISSUE TITLE
Exporting android error with auto-load files

### ISSUE THREAD

**Issue by homarox** [kloder-games/godot-admob#39]
**OS target (Android/iOS):**
Android

**Godot version:**
Godot 3.0.6

**Issue description:**

Logcat output seems to conflict with autoloading files:

> --------- beginning of system
> --------- beginning of main
> 08-23 15:56:29.804 19519 19535 I godot   : Loading module: org/godotengine/godot/GodotAdMob
> 08-23 15:56:29.828 19519 19535 I godot   : OpenGL ES 3.0 Renderer: Mali-T760
> 08-23 15:56:30.666 19519 19535 E godot   : **SCRIPT ERROR**: Parse Error: Unexpected token: ',':Node
> 08-23 15:56:30.666 19519 19535 E godot   :    At: res://utility/game.gdc:2:GDScript::load_byte_code() - Parse Error: Unexpected token: ',':Node
> 08-23 15:56:30.666 19519 19535 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.666 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:777:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.666 19519 19535 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.666 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:2127:load() - Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.666 19519 19535 E godot   : **ERROR**: Failed loading resource: res://utility/game.gdc
> 08-23 15:56:30.666 19519 19535 E godot   :    At: core/io/resource_loader.cpp:190:_load() - Method/Function Failed, returning: RES()
> 08-23 15:56:30.666 19519 19535 E godot   : **ERROR**: Can't autoload: res://utility/game.gd
> 08-23 15:56:30.666 19519 19535 E godot   :    At: main/main.cpp:1498:start() - Condition ' res.is_null() ' is true. Continuing..:
> 08-23 15:56:30.666 19519 19535 E godot   : **SCRIPT ERROR**: Parse Error: Unexpected token: ',':Node
> 08-23 15:56:30.666 19519 19535 E godot   :    At: res://utility/utils.gdc:2:GDScript::load_byte_code() - Parse Error: Unexpected token: ',':Node
> 08-23 15:56:30.666 19519 19535 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.666 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:777:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.666 19519 19535 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.666 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:2127:load() - Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.666 19519 19535 E godot   : **ERROR**: Failed loading resource: res://utility/utils.gdc
> 08-23 15:56:30.666 19519 19535 E godot   :    At: core/io/resource_loader.cpp:190:_load() - Method/Function Failed, returning: RES()
> 08-23 15:56:30.666 19519 19535 E godot   : **ERROR**: Can't autoload: res://utility/utils.gd
> 08-23 15:56:30.666 19519 19535 E godot   :    At: main/main.cpp:1498:start() - Condition ' res.is_null() ' is true. Continuing..:
> 08-23 15:56:30.667 19519 19535 E godot   : **SCRIPT ERROR**: Parse Error: Class 'Node' shadows a native class.
> 08-23 15:56:30.667 19519 19535 E godot   :    At: res://utility/setting.gdc:1:GDScript::load_byte_code() - Parse Error: Class 'Node' shadows a native class.
> 08-23 15:56:30.667 19519 19535 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.667 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:777:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.667 19519 19535 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.667 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:2127:load() - Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.667 19519 19535 E godot   : **ERROR**: Failed loading resource: res://utility/setting.gdc
> 08-23 15:56:30.667 19519 19535 E godot   :    At: core/io/resource_loader.cpp:190:_load() - Method/Function Failed, returning: RES()
> 08-23 15:56:30.667 19519 19535 E godot   : **ERROR**: Can't autoload: res://utility/setting.gd
> 08-23 15:56:30.667 19519 19535 E godot   :    At: main/main.cpp:1498:start() - Condition ' res.is_null() ' is true. Continuing..:
> 08-23 15:56:30.668 19519 19535 E godot   : **SCRIPT ERROR**: Parse Error: Unexpected token: ',':Node
> 08-23 15:56:30.668 19519 19535 E godot   :    At: res://utility/stage_manager.gdc:2:GDScript::load_byte_code() - Parse Error: Unexpected token: ',':Node
> 08-23 15:56:30.668 19519 19535 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.668 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:777:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.668 19519 19535 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.668 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:2127:load() - Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.668 19519 19535 E godot   : **ERROR**: Failed loading resource: res://utility/stage_manager.gdc
> 08-23 15:56:30.668 19519 19535 E godot   :    At: core/io/resource_loader.cpp:190:_load() - Method/Function Failed, returning: RES()
> 08-23 15:56:30.668 19519 19535 E godot   : **ERROR**: res://utility/stage_manager.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://utility/stage_manager.gd
> 08-23 15:56:30.668 19519 19535 E godot   :    At: scene/resources/scene_format_text.cpp:439:poll() - res://utility/stage_manager.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://utility/stage_manager.gd
> 08-23 15:56:30.668 19519 19535 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.668 19519 19535 E godot   :    At: core/io/resource_loader.cpp:153:load() - Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.668 19519 19535 E godot   : **ERROR**: Failed loading resource: res://utility/stage_manager.tscn
> 08-23 15:56:30.668 19519 19535 E godot   :    At: core/io/resource_loader.cpp:190:_load() - Method/Function Failed, returning: RES()
> 08-23 15:56:30.668 19519 19535 E godot   : **ERROR**: Can't autoload: res://utility/stage_manager.tscn
> 08-23 15:56:30.668 19519 19535 E godot   :    At: main/main.cpp:1498:start() - Condition ' res.is_null() ' is true. Continuing..:
> 08-23 15:56:30.733 19519 19535 E godot   : **SCRIPT ERROR**: Parse Error: Class 'Node' shadows a native class.
> 08-23 15:56:30.733 19519 19535 E godot   :    At: res://stages/menu_stage.gdc:1:GDScript::load_byte_code() - Parse Error: Class 'Node' shadows a native class.
> 08-23 15:56:30.733 19519 19535 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.733 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:777:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 08-23 15:56:30.733 19519 19535 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.733 19519 19535 E godot   :    At: modules/gdscript/gdscript.cpp:2127:load() - Condition ' err != OK ' is true. returned: RES()
> 08-23 15:56:30.733 19519 19535 E godot   : **ERROR**: Failed loading resource: res://stages/menu_stage.gdc
> 08-23 15:56:30.733 19519 19535 E godot   :    At: core/io/resource_loader.cpp:190:_load() - Method/Function Failed, returning: RES()
> 08-23 15:56:30.733 19519 19535 E godot   : **ERROR**: res://stages/menu_stage.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://stages/menu_stage.gd
> 08-23 15:56:30.733 19519 19535 E godot   :    At: scene/resources/scene_format_text.cpp:439:poll() - res://stages/menu_stage.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://stages/menu_stage.gd
> 
FULL LOG: [https://app.box.com/s/aoo8asvtrk1tztg1vuvou896uwu5ik3v](url)

**Comment by Shin-NiL** [comment]
It seems like there's a comma left somewhere. 

How's these lines in your `project.godot `file?
```
[android]
modules="org/godotengine/godot/GodotAdMob"
```

**Comment by homarox** [comment]
I re-compile with Godot version 3.0.2 and it's working

**Comment by Shin-NiL** [comment]
Does your template work if you use 3.0.6 and disable the Admob module?

**Comment by homarox** [comment]
Yes, It's working with 3.0.6 & disable Admob module, but Admob only working with export with Godot 3.0.2 :(

**Comment by Shin-NiL** [comment]
Well, it's really unexpected. I'll take a look at this when I can.

**Comment by Shin-NiL** [comment]
I've tested the Admob demo project with Godot 3.0.6 and is working fine. Could you do the same?

**Comment by homarox** [comment]
Sadly no, 
Could you upload debug and release file that you export in 3.0.6?
I will test on my device.

**Comment by Shin-NiL** [comment]
I only have the release template, but for testing purposes you can use it for both, release & debug.
[android_release.apk.zip](https://github.com/kloder-games/godot-admob/files/2327689/android_release.apk.zip)

**Comment by homarox** [comment]
Hi Shin-NiL,
I implemented your release and It's working well. 
I will check from my side.
Thank you very much :)

**Comment by Shin-NiL** [comment]
Nice :)
