### ISSUE TITLE
Android build error message - (gradlew build)

### ISSUE THREAD

**Issue by osimuka** [kloder-games/godot-admob#40]
I get this error message when I run the godot build for android_debug.apk and android_release.
The fix is to remove the @override decorator... is this intended?
GodotAdMob.java:111: error: method does not override or implement a method from a supertype

**Comment by Shin-NiL** [comment]
You're using an Google Mobile SDK older than 12.0.0. Make sure your internet is working when running gradlew build, this way you can get the newer version (15.0.0)

**Comment by osimuka** [comment]
Cool, thanks for pointing that out
