### ISSUE TITLE
iOS Admob Problem

### ISSUE THREAD

**Issue by ermantepe** [kloder-games/godot-admob#43]
**OS target (Android/iOS):**
iOS

**Godot version:**
3.06

**Issue description:**
I'm using Godot 3.0.6 and using iPad 6th Generation

For iOS I have some questions.

First, I recompiled the iOS export template with admob module and I have lost of exports. Lol. :D And I don't understand, which one I'll use and how?

I have now:

- godot.iphone.opt.universal
- libgodot.android.opt.armv7.neon.so
- libgodot.iphone.debug.arm64.a
- libgodot.iphone.debug.x86.a
- libgodot.iphone.opt.arm.a
- libgodot.iphone.opt.arm64.a

I exported my project from Godot, now I have a XCode Project and it is working on real device but Ads are not showing.

In the readme file, there is a information;

-Copy the library (.a) you have compiled following the official documentation inside the exported Xcode project. You must override the 'your_project_name.a' file with this file.

Which file should I use? When I try replace my FlappyHorse.a with libgodot.iphone.op.arm64.a or godot.iphone.opt.universal (replaced name with FlappyHorse.a) I am getting error that you can find below.

I downloaded GoogleMobileAds.framework from there: https://developers.google.com/admob/ios/download

Ld /Users/***/Library/Developer/Xcode/DerivedData/FlappyHorse-chjapgceylflyjcxvuoowpmjhvxf/Build/Products/Debug-iphoneos/FlappyHorse.app/FlappyHorse normal arm64 (in target: FlappyHorse)

cd /Users/*****/Documents/Projects/Flappy\ Horse/ios_export

export IPHONEOS_DEPLOYMENT_TARGET=9.0

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk -L/Users/tepee/Library/Developer/Xcode/DerivedData/FlappyHorse-chjapgceylflyjcxvuoowpmjhvxf/Build/Products/Debug-iphoneos -F/Users/tepee/Library/Developer/Xcode/DerivedData/FlappyHorse-chjapgceylflyjcxvuoowpmjhvxf/Build/Products/Debug-iphoneos -FFlappyHorse -F/Users/tepee/Documents/Projects/Flappy\ Horse/ios_export -filelist /Users/tepee/Library/Developer/Xcode/DerivedData/FlappyHorse-chjapgceylflyjcxvuoowpmjhvxf/Build/Intermediates.noindex/FlappyHorse.build/Debug-iphoneos/FlappyHorse.build/Objects-normal/arm64/FlappyHorse.LinkFileList -miphoneos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/tepee/Library/Developer/Xcode/DerivedData/FlappyHorse-chjapgceylflyjcxvuoowpmjhvxf/Build/Intermediates.noindex/FlappyHorse.build/Debug-iphoneos/FlappyHorse.build/Objects-normal/arm64/FlappyHorse_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -stdlib=libc++ -framework MobileCoreServices -framework CFNetwork -framework CoreTelephony -framework MessageUI -framework AdSupport -framework CoreVideo -framework GoogleMobileAds -framework CoreGraphics -framework SystemConfiguration -framework Security -framework QuartzCore -framework MediaPlayer -framework GameController -framework CoreMotion -framework CoreMedia -framework CoreAudio -framework AudioToolbox -framework OpenGLES -framework StoreKit -framework AVFoundation -framework UIKit -framework GameKit -framework GLKit -framework Foundation /Users/tepee/Documents/Projects/Flappy\ Horse/ios_export/FlappyHorse.a -Xlinker -dependency_info -Xlinker /Users/tepee/Library/Developer/Xcode/DerivedData/FlappyHorse-chjapgceylflyjcxvuoowpmjhvxf/Build/Intermediates.noindex/FlappyHorse.build/Debug-iphoneos/FlappyHorse.build/Objects-normal/arm64/FlappyHorse_dependency_info.dat -o /Users/tepee/Library/Developer/Xcode/DerivedData/FlappyHorse-chjapgceylflyjcxvuoowpmjhvxf/Build/Products/Debug-iphoneos/FlappyHorse.app/FlappyHorse

Undefined symbols for architecture arm64:

"_sqlite3_open", referenced from:

l150 in GoogleMobileAds(GADNSettings.o)

l087 in GoogleMobileAds(GADNSQLStorage.o)

"_sqlite3_exec", referenced from:

l150 in GoogleMobileAds(GADNSettings.o)

l087 in GoogleMobileAds(GADNSQLStorage.o)

"_sqlite3_errmsg", referenced from:

l203 in GoogleMobileAds(GADNSettings.o)

l107 in GoogleMobileAds(GADNSQLStorage.o)

"_sqlite3_prepare_v2", referenced from:

l149 in GoogleMobileAds(GADNSettings.o)

l203 in GoogleMobileAds(GADNSettings.o)

l086 in GoogleMobileAds(GADNSQLStorage.o)

l107 in GoogleMobileAds(GADNSQLStorage.o)

"_sqlite3_step", referenced from:

l149 in GoogleMobileAds(GADNSettings.o)

l203 in GoogleMobileAds(GADNSettings.o)

l086 in GoogleMobileAds(GADNSQLStorage.o)

l107 in GoogleMobileAds(GADNSQLStorage.o)

"_sqlite3_bind_text", referenced from:

l203 in GoogleMobileAds(GADNSettings.o)

l107 in GoogleMobileAds(GADNSQLStorage.o)

"_sqlite3_column_text", referenced from:

l149 in GoogleMobileAds(GADNSettings.o)

l086 in GoogleMobileAds(GADNSQLStorage.o)

"_sqlite3_finalize", referenced from:

l149 in GoogleMobileAds(GADNSettings.o)

l203 in GoogleMobileAds(GADNSettings.o)

l086 in GoogleMobileAds(GADNSQLStorage.o)

l107 in GoogleMobileAds(GADNSQLStorage.o)

"_sqlite3_close", referenced from:

l148 in GoogleMobileAds(GADNSettings.o)

l150 in GoogleMobileAds(GADNSettings.o)

l085 in GoogleMobileAds(GADNSQLStorage.o)

l087 in GoogleMobileAds(GADNSQLStorage.o)

ld: symbol(s) not found for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ermantepe** [comment]
Ok, problem solved. I added sqlite lib.

**Comment by Shin-NiL** [comment]
Thanks, I'll do that.
