### ISSUE TITLE
The Example for godot 3 won't work

### ISSUE THREAD

**Issue by MrZak-dev** [kloder-games/godot-admob#46]
**OS target (Android/iOS):**
Android

**Godot version:**
3.0.6 stable

**Issue description:**

I compiled godot source code with admob module and i set the exported apks .
i tried to run the example app and it won't work .

adb logcat
 

 ![adb](https://i.imgur.com/CMPZXPa.jpg)

**Comment by Shin-NiL** [comment]
Are you using your custom compiled template for both (release and debug) export option?

**Comment by MrZak-dev** [comment]
yes 
the command i used is `scons platform=android target=release_debug`
and i set the apks for both debug and relese .

**Comment by Shin-NiL** [comment]
I've pushed a new commit, download this module source, drop the "admob" directory inside the "modules" directory on your Godot source code and try compile again.

**Comment by MrZak-dev** [comment]
Same Error : 


![error](https://i.imgur.com/FUq1GhC.png)

**Comment by Shin-NiL** [comment]
I've compiled the Godot 3.0.6-stable and the demo worked just fine here, I can't reproduce the issue. Please double check each step described on readme file.

**Comment by MrZak-dev** [comment]
it worked just fine , thank's a lot :+1:
