### ISSUE TITLE
'Node2D' shadows a native class

### ISSUE THREAD

**Issue by phaitonican** [kloder-games/godot-admob#50]
**OS target (Android/iOS):** Android

**Godot version:** V3.0.6.stable

**Issue description:**

Recompiled android_release.apk and android_debug.apk with the source of Godot and dropped admob folder in modules.
Export works fine but when I launch the app:

> 11-03 03:55:09.701 25242 25263 E godot   : **SCRIPT ERROR**: Parse Error: Class 'Node2D' shadows a native class.
> 11-03 03:55:09.701 25242 25263 E godot   :    At: res://Menu.gdc:1:GDScript::load_byte_code() - Parse Error: Class 'Node2D' shadows a native class.
> 11-03 03:55:09.701 25242 25263 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 11-03 03:55:09.701 25242 25263 E godot   :    At: modules/gdscript/gdscript.cpp:768:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 11-03 03:55:09.719 25242 25263 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:09.719 25242 25263 E godot   :    At: modules/gdscript/gdscript.cpp:2120:load() - Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:09.757 25242 25263 E godot   : **ERROR**: Failed loading resource: res://Menu.gdc
> 11-03 03:55:09.769 25242 25263 E godot   :    At: core/io/resource_loader.cpp:192:_load() - Method/Function Failed, returning: RES()
> 11-03 03:55:09.780 25242 25263 E godot   : **ERROR**: res://Menu.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Menu.gd
> 11-03 03:55:09.780 25242 25263 E godot   :    At: scene/resources/scene_format_text.cpp:439:poll() - res://Menu.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Menu.gd
> 11-03 03:55:09.780 25242 25263 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:09.780 25242 25263 E godot   :    At: core/io/resource_loader.cpp:155:load() - Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:09.791 25242 25263 E godot   : **ERROR**: Failed loading resource: res://Menu.tscn
> 11-03 03:55:09.791 25242 25263 E godot   :    At: core/io/resource_loader.cpp:192:_load() - Method/Function Failed, returning: RES()
> 11-03 03:55:09.804 25242 25263 E godot   : **ERROR**: Failed loading scene: res://Menu.tscn
> 11-03 03:55:09.804 25242 25263 E godot   :    At: main/main.cpp:1719:start() - Condition ' !scene ' is true. returned: false
> 11-03 03:55:21.528 25242 25263 E godot   : **SCRIPT ERROR**: Parse Error: Class 'Node2D' shadows a native class.
> 11-03 03:55:21.528 25242 25263 E godot   :    At: res://Menu.gdc:1:GDScript::load_byte_code() - Parse Error: Class 'Node2D' shadows a native class.
> 11-03 03:55:21.528 25242 25263 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 11-03 03:55:21.528 25242 25263 E godot   :    At: modules/gdscript/gdscript.cpp:768:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 11-03 03:55:21.537 25242 25263 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:21.537 25242 25263 E godot   :    At: modules/gdscript/gdscript.cpp:2120:load() - Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:21.599 25242 25263 E godot   : **ERROR**: Failed loading resource: res://Menu.gdc
> 11-03 03:55:21.605 25242 25263 E godot   :    At: core/io/resource_loader.cpp:192:_load() - Method/Function Failed, returning: RES()
> 11-03 03:55:21.673 25242 25263 E godot   : **ERROR**: res://Menu.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Menu.gd
> 11-03 03:55:21.674 25242 25263 E godot   :    At: scene/resources/scene_format_text.cpp:439:poll() - res://Menu.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Menu.gd
> 11-03 03:55:21.674 25242 25263 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:21.674 25242 25263 E godot   :    At: core/io/resource_loader.cpp:155:load() - Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:21.698 25242 25263 E godot   : **ERROR**: Failed loading resource: res://Menu.tscn
> 11-03 03:55:21.698 25242 25263 E godot   :    At: core/io/resource_loader.cpp:192:_load() - Method/Function Failed, returning: RES()
> 11-03 03:55:21.740 25242 25263 E godot   : **ERROR**: Failed loading scene: res://Menu.tscn
> 11-03 03:55:21.740 25242 25263 E godot   :    At: main/main.cpp:1719:start() - Condition ' !scene ' is true. returned: false
> 11-03 03:55:33.198 25242 25263 E godot   : **SCRIPT ERROR**: Parse Error: Class 'Node2D' shadows a native class.
> 11-03 03:55:33.198 25242 25263 E godot   :    At: res://Menu.gdc:1:GDScript::load_byte_code() - Parse Error: Class 'Node2D' shadows a native class.
> 11-03 03:55:33.198 25242 25263 E godot   : **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
> 11-03 03:55:33.198 25242 25263 E godot   :    At: modules/gdscript/gdscript.cpp:768:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
> 11-03 03:55:33.217 25242 25263 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:33.217 25242 25263 E godot   :    At: modules/gdscript/gdscript.cpp:2120:load() - Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:33.256 25242 25263 E godot   : **ERROR**: Failed loading resource: res://Menu.gdc
> 11-03 03:55:33.300 25242 25263 E godot   :    At: core/io/resource_loader.cpp:192:_load() - Method/Function Failed, returning: RES()
> 11-03 03:55:33.334 25242 25263 E godot   : **ERROR**: res://Menu.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Menu.gd
> 11-03 03:55:33.334 25242 25263 E godot   :    At: scene/resources/scene_format_text.cpp:439:poll() - res://Menu.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Menu.gd
> 11-03 03:55:33.334 25242 25263 E godot   : **ERROR**: Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:33.334 25242 25263 E godot   :    At: core/io/resource_loader.cpp:155:load() - Condition ' err != OK ' is true. returned: RES()
> 11-03 03:55:33.472 25242 25263 E godot   : **ERROR**: Failed loading resource: res://Menu.tscn
> 11-03 03:55:33.472 25242 25263 E godot   :    At: core/io/resource_loader.cpp:192:_load() - Method/Function Failed, returning: RES()
> 11-03 03:55:33.478 25242 25263 E godot   : **ERROR**: Failed loading scene: res://Menu.tscn
> 11-03 03:55:33.478 25242 25263 E godot   :    At: main/main.cpp:1719:start() - Condition ' !scene ' is true. returned: false

**Comment by vgmoose** [comment]
Did you ever find out what the error was here?
