### ISSUE TITLE
Admob ios xcode compile error

### ISSUE THREAD

**Issue by osimuka** [kloder-games/godot-admob#51]
**OS target (iOS):**
Im getting this error message when I try to build my project with admob for the iOS

**Godot version:**
3.0.6

**Issue description:**

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:
      objc-class-ref in application_name.a(AdmobRewarded.iphone.opt.debug.arm64.o)
  "_OBJC_CLASS_$_GADInterstitial", referenced from:
      objc-class-ref in application_name.a(AdmobInterstitial.iphone.opt.debug.arm64.o)
  "_OBJC_CLASS_$_GADBannerView", referenced from:
      objc-class-ref in application_name.a(AdmobBanner.iphone.opt.debug.arm64.o)
  "_OBJC_CLASS_$_GADRequest", referenced from:
      objc-class-ref in application_name.a(AdmobBanner.iphone.opt.debug.arm64.o)
      objc-class-ref in application_name.a(AdmobInterstitial.iphone.opt.debug.arm64.o)
      objc-class-ref in application_name.a(AdmobRewarded.iphone.opt.debug.arm64.o)
  "_kGADAdSizeSmartBannerPortrait", referenced from:
      -[AdmobBanner loadBanner::] in application_name.a(AdmobBanner.iphone.opt.debug.arm64.o)
  "_kGADAdSizeSmartBannerLandscape", referenced from:
      -[AdmobBanner loadBanner::] in application_name.a(AdmobBanner.iphone.opt.debug.arm64.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by osimuka** [comment]
Issue was caused because of bug in xcode for not recognising the inclusion of the GoogleMobileAds.framework in the linked framework and libraries.
So this issue is closed

**Comment by Shin-NiL** [comment]
Thanks for reporting.

**Comment by wombatwingdings** [comment]
I'm having the same problem. How do you work round it?

Thanks!

**Comment by osimuka** [comment]
It’s kind of cliche with Xcode, have you installed the SDK for admob for
iOS?

**Comment by wombatwingdings** [comment]
Yes. I have it here:
$ pwd
/Users/xxx/godot/modules/admob/ios/lib
$ ls
GoogleMobileAds.framework		put_GoogleMobileAds.framework_here

Unless maybe the contents of GoogleMobileAds.framework should be at this level?

**Comment by osimuka** [comment]
Cool that’s perfect, ok try adding it as the top framework on your Xcode
modules. If it was there already remove it and add it again.

**Comment by wombatwingdings** [comment]
I see what you mean now. Easily worked around inside Xcode. Thanks very much for your help!
