### ISSUE TITLE
How can I use "max_ad_content_rating" parameter?

### ISSUE THREAD

**Issue by elilan** [kloder-games/godot-admob#54]
**OS target (Android/iOS):**

**Godot version:**

**Issue description:**
Hello. Thanks for this module. I have two questions.
1. I am new here and I dont know if I can create a question that is not an issue. Therefore, I created an issue. Is it right?
2. On the [Google documentation about AdMob](https://support.google.com/admob/answer/7562142?hl=en) there is a reference to "max_ad_content_rating" parameter in each request to AdMob. Can I use this parameter in this module in some way?
Thanks in advance.

**Comment by Shin-NiL** [comment]
Hello there my friend ;)
 1. Yes, it's okay to ask questions here.
 2. This module only exposes the most used features from Admob SDK (it works like a bridge) and the "max_ad_content_rating" isn't mapped. The best solution here seems to be to set this value in your Admob backend per individual app, as suggested in the link you sent us.

**Comment by elilan** [comment]
Hello, @Shin-NiL , and thanks for your response.
I understand the situation. The problem is that only few publishers can set max content rating in backend, because this feature is in beta. I am in the large group that does not have this feature enabled.
I already suffered from a banned app because this situation. :( So in my native android apps I changed the code (I added this parameter).
But I am moving to Godot now. :) I plan making a game with "G" rating, and it is not the default for AdMob, so if I did not customize the max rating, my new game will probably be banned again.
Can you guide me in your code, give me an idea about what file/s and function/s I would need to change for map this parameter?

**Comment by Shin-NiL** [comment]
I see...
For what I could see [here](https://developers.google.com/admob/android/targeting#child-directed_setting) for Android, you should change all the AdRequest Builders on [this file](https://github.com/kloder-games/godot-admob/blob/master/admob/android/GodotAdMob.java) to something like this:

**Ad content filtering**
```
Bundle extras = new Bundle();
extras.putString("max_ad_content_rating", "G");

AdRequest request = new AdRequest.Builder()
        .addNetworkExtrasBundle(AdMobAdapter.class, extras)
        .build();
```
**Load an ad with targeting**
```
AdRequest request = new AdRequest.Builder()
        .tagForChildDirectedTreatment(true)
        .build();
adView.loadAd(request);
```

**Comment by elilan** [comment]
Thank you very much!

I will try to modify that file locally.

I compiled Godot with the current version of this module successfuly yesterday. 😄 It's working in my phone now.

Another question.  In the file that you referenced, I see this line (for each request):
`adBuilder.tagForChildDirectedTreatment(true);`

So, If I understand, in the current version of the code, we _allways_ are requesting ads with child directed treatment

- Proposal: if that is the case, it will be great if it is clearified in the docs.

- 2nd proposal: may be we can add one or two more parameters to the _init_ (_isForChildDirectedTreatment_ and _maxAdContentRating_). It's only a proposal.

Thanks again. You are very kind.

**Comment by Shin-NiL** [comment]
> Another question. In the file that you referenced, I see this line (for each request):
adBuilder.tagForChildDirectedTreatment(true);

To be honest, this is the first time I notice this, since that part of the code was not written by me. But yes, the ads are child directed (banner and interstitial only).

Your second proposal looks fine to me, I just need some free time to code it.

**Comment by Shin-NiL** [comment]
That's great, your contribution will be greatly appreciated. Yeah, I don't even have an iOS to test my changes, all the lines I coded was with a borrowed one some time ago. Keeping the two codes (Android & iOS) synchronized will not be a simple task, but it needs to be done that way.

**Comment by elilan** [comment]
I don't have an iOS either.
I can upload my modified file. How will we do the changes? Do we create a new branch for this changes, thinking in future merge with master branch when iOS and Android code will be synchronized?

**Comment by Shin-NiL** [comment]
I created a new branch for these changes in my repository, you can send a pull request there: https://github.com/Shin-NiL/godot-admob/tree/content_rating

**Comment by elilan** [comment]
Thanks.
I sent my pull request in the branch that you referenced.

**Comment by Shin-NiL** [comment]
Nice, I'll review it as soon as possible, thank you very much.

**Comment by elilan** [comment]
You're welcome.

**Comment by Shin-NiL** [comment]
Just merged your changes, thank you again ;)
