### ISSUE TITLE
Xcode build failing: ld: framework not found GoogleMobileAds

### ISSUE THREAD

**Issue by gvdb** [kloder-games/godot-admob#57]
**OS target (Android/iOS):** iOS

**Godot version:** 3.0.6

**Issue description:**
I followed the steps on the readme page for iOS but got this error when building the project.

`ld: framework not found GoogleMobileAds`

Not sure why it can't find that framework. I added GoogleMobileAds.framework to the xcode project under the Frameworks directory, and checked that it's linked with the Libraries under Build Phases.

It seems similar to issue #43, but I've linked both libsqlite3*.tbd binaries with Libraries. Unfortunately that hasn't resolved the issue for me.

**Edit:** Not sure if this extra info is helpful, but I built the Godot Engine source with:

`scons p=iphone tools=no bits=64 target=release_debug arch=arm64`

And copied `bin/libgodot.iphone.opt.debug.arm64.a` from the Godot Engine source to the xcode project, overwriting the *.a file that was there.

**Comment by gvdb** [comment]
I think I've managed to solve this particular issue. It was Xcode not behaving as I expected.

Manually placing the framework file in the Xcode project directory, THEN manually linking to THAT copied file fixed the issue.

For some reason dragging and dropping the framework file from my Downloads directory from Finder into Xcode project navigator didn't work. I think it was creating a reference to the file in Downloads, but Xcode couldn't actually find it.

Sorry for the non-issue. Hopefully this helps someone else with debugging.

**Comment by Shin-NiL** [comment]
Thanks for reporting your solution.
