### ISSUE TITLE
AdMob not showing ads in alpha for other phones

### ISSUE THREAD

**Issue by reyalpsirc** [kloder-games/godot-admob#58]
**OS target (Android/iOS):**
Android

**Godot version:**
2.1.4 custom build

**Issue description:**
I tried the code on my device and installed it through ADB and everything was working okay with the Ads but, as soon as I uploaded it to the AppStore Alpha, I tested on some friend's devices and the Ads were not working.
Checking the logs I got the following error:

	12-07 09:36:19.281  21102    21102                    Ads  I  Updating ad debug logging enablement.
	12-07 09:36:19.291   3824     4812        ActivityManager  W  Unable to start service Intent { act=com.google.android.gms.ads.identifier.service.START pkg=com.google.android.gms } U=0: not found
	12-07 09:36:19.291  21102    21159                    Ads  E  Fail to get isAdIdFakeForDebugLogging
	12-07 09:36:19.291  21102    21159                    Ads  E  java.io.IOException: Connection failure
	12-07 09:36:19.291  21102    21159                    Ads  E  at com.google.android.gms.ads.identifier.a.a(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):106)
	12-07 09:36:19.291  21102    21159                    Ads  E  at com.google.android.gms.ads.identifier.a.a(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):16)
	12-07 09:36:19.291  21102    21159                    Ads  E  at com.google.android.gms.ads.identifier.a.b(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):131)
	12-07 09:36:19.291  21102    21159                    Ads  E  at com.google.android.gms.ads.internal.util.d.c_(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):3)
	12-07 09:36:19.291  21102    21159                    Ads  E  at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):4)
	12-07 09:36:19.291  21102    21159                    Ads  E  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	12-07 09:36:19.291  21102    21159                    Ads  E  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	12-07 09:36:19.291  21102    21159                    Ads  E  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	12-07 09:36:19.291  21102    21159                    Ads  E  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	12-07 09:36:19.291  21102    21159                    Ads  E  at java.lang.Thread.run(Thread.java:818)
	12-07 09:36:19.291  21102    21159                    Ads  W  Update ad debug logging enablement as false
	12-07 09:36:19.331  21102    21102                    Ads  I  Starting ad request.
	12-07 09:36:19.331  21102    21102                    Ads  I  SDK version: afma-sdk-a-v14799019.10084000.1

Any idea of what can cause this? What am I missing?

**Comment by Shin-NiL** [comment]
Are the first parameter (isReal) from init true of false? Some devices can't display the test ads, only the real ones (I don't know why).

**Comment by Shin-NiL** [comment]
It should have worked then. I've never seen this kind of issue.

**Comment by reyalpsirc** [comment]
@Shin-NiL This is the code I have on startup of the game (on my config.gd file which is autoloading at start with the game):

	var isReal = true
	var adInterstitialId = "xxxxxxxx"
	if (OS.get_name()=="iOS" or OS.get_name()=="Android"):
		if(Globals.has_singleton("AdMob")):
			googleAdMob = Globals.get_singleton("AdMob")
			googleAdMob.init(isReal, get_instance_ID())
			googleAdMob.loadInterstitial(adInterstitialId)

And this is the code I have when entering a level from time to time:

	if (config.googleAdMob):
		config.googleAdMob.showInterstitial()
		return;

**Comment by Shin-NiL** [comment]
The code seems ok to me.
What happens if you download the beta app from Google Play and install on your device? Does it work?

**Comment by reyalpsirc** [comment]
I just tried on a friends phone and the ads still don't display neither in test mode...
The logs have the following line when calling the `showInterstitial `:

`Ad failed to load : 0`

I searched around but did not get any solution so far since the interstitial ID was created over an year ago and the payments info is in place

**Comment by Shin-NiL** [comment]
@reyalpsirc you don't need to insert the App ID as we are using Admob SDK 16.

**Comment by rgoncalves83** [comment]
Thanks @Shin-NiL!!

**Comment by reyalpsirc** [comment]
@Shin-NiL I just tried with the examples provided at https://github.com/googleads/googleads-mobile-android-examples/releases/tag/5.3 and they don't work either with my ids or their ids... Do you know if Admob is still working well lately with previous Ids and such?

**Comment by Shin-NiL** [comment]
@reyalpsirc I've some apps published and they're working fine, including interstitials.

**Comment by reyalpsirc** [comment]
This was indeed a problem with AdMob itself. I provided some logs and such to the AdMob’s team and it seems working now without changes on this library :)

**Comment by Shin-NiL** [comment]
@reyalpsirc Thanks for reporting.
