### ISSUE TITLE
Compilation Error: register_types.cpp not finding include file version_generated.gen.h

### ISSUE THREAD

**Issue by wombatwingdings** [kloder-games/godot-admob#61]
**OS target (Android/iOS):**
OSX & iOS

**Godot version:**
3.1 latest source from master branch today

**Issue description:**
I can build OSX Godot and iOS export modules fine. But when I add this module, I get compilation error unable to find "version_generated.gen.h" file:

[ 13%] Compiling ==> modules/admob/register_types.cpp
modules/admob/register_types.cpp:1:10: fatal error: 'version_generated.gen.h' file not found
#include <version_generated.gen.h>

I have the "admob" directory in the Godot "modules" directory and have dropped Google Mobile Ads SDK in the ios/lib dir.

version_generated.gen.h exists in godot/core directory. I have a completely clean build directory pulled from git today. I'm not familiar with scons so don't know where the include directories should be specified. Any help would be appreciated. Thanks!

**Comment by wombatwingdings** [comment]
I have worked round this issue by adding following to config.py:

    env.Append( CPPPATH=['_full_path_to_/godot/core'] )

Probably not the best fix but it seems to work.

**Comment by Shin-NiL** [comment]
Could anybody confirms if it works with just:
```
env.Append(CPPPATH=['/core'])
```
If so I can update the code with this fix.

**Comment by GhostWalker562** [comment]
Where exactly do we put this line of code? I'm willing to try both, and I have but it doesn't seem to fix the error for me at least.

**Comment by Shin-NiL** [comment]
It should be in the file ```admob/config.py```, line 13, just after 
```
	env.Append(FRAMEWORKPATH=['modules/admob/ios/lib'])
```
Something like this: https://pastebin.com/SmCtKkD4

**Comment by Shin-NiL** [comment]
@GhostWalker562 nevermind, just updated the repository, try again with my last commit.

**Comment by GhostWalker562** [comment]
Works 👍

**Comment by Shin-NiL** [comment]
@GhostWalker562 Nice, thanks for testing! 
As I mentioned before, I don't have any Apple hardware to maintain and test this module for iOS. I wrote this for a project some time ago and borrowed a mac mini to do the development.
