### ISSUE TITLE
Compiling Godot for Android 

### ISSUE THREAD

**Issue by Lucky0710** [kloder-games/godot-admob#63]
Hi everyone, 
I recently tried to compile godot for android because i want to implement admob on my first game !
But i'm really struggling to do so, and i just can't figure out why it is not working, it seems like a new problems appears right after i find a solution to the previous one...

I'm clearly missing something, so if anyone managed to recently compile godot for android, it would be amazing if he could tell me exactly the process he went through, and the version of the NDK, SDK, JDK, Scons etc, he's using. 

I really want to launch this game i've developped for so long, and this would help me so much !
Thanks in advance !

(sorry for my english, it is not my first langage...)

**Comment by Shin-NiL** [comment]
No prob.
