### ISSUE TITLE
Example project crashes on start up.

### ISSUE THREAD

**Issue by ca3games** [kloder-games/godot-admob#66]
**OS target (Android/iOS):**
Android

**Godot version:**
3.0.6 stable

**Issue description:**
Example project crash on startup.

I followed the guide and Used the apks from here: https://github.com/Shin-NiL/godot-custom-mobile-template

Then I added on the example project the google test banner IDs and add permissions of Internet and Access Network State.

However the project compiles and install the apk on my phone, but it crashes on start up.

**Comment by Shin-NiL** [comment]
Just tested here and it worked fine. Maybe your device doesn't support OpenGL ES 3, it's a serious issue with Godot 3.0.* and will be fixed on 3.1.0.

**Comment by ca3games** [comment]
> Just tested here and it worked fine. Maybe your device doesn't support OpenGL ES 3, it's a serious issue with Godot 3.0.* and will be fixed on 3.1.0.
> 
> Try to run a project with just an empty scene using Godot 3.0.6 and the official templates. If it crashes, the lack of OpenGL ES 3 is likely the problem.

Yes, my phone lacks GL 3, but when I tried to port the example using Godot 3.1 beta, it complained the apk were corrupted.

**Comment by Shin-NiL** [comment]
Yeah, the template compiled for 3.0.6 will not work on games made using 3.1. Once we have a stable version of 3.1 I'll upload the new templates.
