### ISSUE TITLE
Google Ads not showing

### ISSUE THREAD

**Issue by Lucky0710** [kloder-games/godot-admob#67]
Hi ! 
i'm using:
Windows 10, Godot 3.0.6

Compiling Godot with and without admob works really fine, test ads are showing, good !

But the problem is when i try to show real ads with the IDs i get from my Google ads account, the app works find, the ads are loaded successfuly, but no ads shows up...

**Comment by Shin-NiL** [comment]
Android or iOS?
Are your ad ids new?

**Comment by Lucky0710** [comment]
Android ! 
and i created my ad ids yesterday.

**Comment by Shin-NiL** [comment]
Please check the logs with adb (as stated on the README) and post the output here.

**Comment by Lucky0710** [comment]
I am getting this : 

02-09 20:01:19.964 27911-28178/org.godotengine.collide W/Ads: Not retrying to fetch app settings
02-09 20:01:22.834 27911-27911/org.godotengine.collide W/godot: AdMob: onAdFailedToLoad(int errorCode) - error code: 3
02-09 20:01:22.834 27911-27911/org.godotengine.collide W/godot: AdMob: _on_interstitial_not_loaded
02-09 20:01:22.834 27911-27911/org.godotengine.collide I/Ads: Ad failed to load : 3
02-09 20:01:22.884 27911-27911/org.godotengine.collide W/godot: AdMob: onAdFailedToLoad -> ERROR_CODE_NO_FILL
02-09 20:01:22.884 27911-27911/org.godotengine.collide I/Ads: Ad failed to load : 3

The strange this is, a banner ad appeared in one of my tests, but i cannot make it reapear now

**Comment by Shin-NiL** [comment]
As stated in the Known Issues (README file) it's a google Admob issue, most of the times it works after some time.

**Comment by Lucky0710** [comment]
Oh ok.. So i will test it tomorow and hope it will go away, thanks !

**Comment by RtgApps** [comment]
Hello, 
thank you for helping us with our issues.
How can I remove the tiny label "Test Ad"? The real ad is already showing and it works. But there is still the "Test Ad" label at the top of my banner and i don't know how to deleted it. Thank you

**Comment by gustavottc** [comment]
It's not possible to remove test ads on debugging and test with test unit id mode, this will be automatic removed when your game is published on Google Play or App Store with real unit id ads

**Comment by gustavottc** [comment]
So don't worry about the "Test Ad" label, this wont appear on apps released on Google Play or App Store

**Comment by RtgApps** [comment]
Alright, thank you for your help

Am Sa., 23. Mai 2020 um 17:32 Uhr schrieb Gustavo Maciel <
notifications@github.com>:

**Comment by RtgApps** [comment]
Hi, it's me again, my app is now online but the "Test Ad" label is still
showing, Any idea how to fix this problem? Thanks

Am Sa., 23. Mai 2020 um 18:51 Uhr schrieb B El <benjamin.elh@gmail.com>:

**Comment by gustavottc** [comment]
Did you put a real ads and disabled the variable isReal?

**Comment by RtgApps** [comment]
the real ads are active. I set the isReal boolean on true and deleted the
Strings (the test ad ids) and added my own ids . Am I supposed to disable
the Variable isReal ?

Gustavo Maciel <notifications@github.com> schrieb am Di. 2. Juni 2020 um
00:18:

**Comment by RtgApps** [comment]
Im using a new version of it, it seems to work, Thank you

B El <benjamin.elh@gmail.com> schrieb am Di. 2. Juni 2020 um 10:27:
