### ISSUE TITLE
Real ads showing very rarely

### ISSUE THREAD

**Issue by Lucky0710** [kloder-games/godot-admob#69]
Hi ! 
I'm using windows 10, Godot 3.0.6
Godot compile successfuly with the admob module, test ads work perfectly fine !
But when i try to use real ads (banner and intersticial), only one over 300 ad is showing and it is only a banner ad, no intersticials. (also my code works perfectly for test ads)

Logcat throw me this error : 
AdMob: onAdFailedToLoad -> ERROR_CODE_NO_FILL
Ad failed to load : 3

I created my account like 7 days ago, and sometimes an ad actually shows, witch i find weird...

**Comment by Shin-NiL** [comment]
I'm really sorry, but there's nothing we can do. As I said before on the issue #67 (and README file) it's a issue with the admob backend. It occurs most likely because there's no ads to be shown to your country or region. It's out of our control.
