### ISSUE TITLE
Update template

### ISSUE THREAD

**Issue by salomander86** [kloder-games/godot-admob#7]
Hello! Thanks a lot for your modules! I have some issues with compilation... I suppose the issues are on my side.
Is there a chance you can update the templates for godot 2.1.4-stable? You will save my day ;)

**Comment by Shin-NiL** [comment]
[Here's the one](http://www.mediafire.com/file/ddomuou6j3za3vc/2.1.4-admob-share.apk) I'm using (release mode).

**Comment by tam0705** [comment]
Wow @Shin-NiL  you save my life! I tried to use the template in the repository, I tried to compile the template myself, but everything failed. Can you give the link to your debug template too please? :)

**Comment by Shin-NiL** [comment]
I'm glad to help @tam075. I'm sorry, but I don't have a debug template, in fact I always use just the release one.

**Comment by tam0705** [comment]
Oh okay then, it's fine, @Shin-NiL. I think I'll just do the same :v Once again thank you for sharing the template! :D

**Comment by Applemann** [comment]
@Shin-NiL Why you don't update the templates in this folder: https://github.com/kloder-games/godot-admob/tree/master/templates  ??

**Comment by Shin-NiL** [comment]
Because git wasn't meant to store binaries. A better place is here: https://github.com/kloder-games/godot-admob/releases but I don't have access to this feature.

**Comment by Applemann** [comment]
Hmm maybe @jlopezcur can you give the access..

**Comment by Shin-NiL** [comment]
Yeah, even so, build the templates for Android, iOS, Godot 2 & 3 would be a tedious work :(
Another problem is that the use of these templates is very limited, because if, for example, you need another module(s), it will not help.

**Comment by jlopezcur** [comment]
I think @Shin-NiL is rigth. Now I don't have time for maintain this repo and @Shin-NiL is doing all the work (Thanks for that and for all the work you do @Shin-NiL ), I have given the admin controll of the repo to him. Despite that as @Shin-NiL say is atedious work and not so useful work becouse of the possible combination with others plugins. There are several ways to achieve this goal (as I see now):
- Port the plugin to the new system of GDNative. I think this could be a possibility but as I said I don't have time right now to try this way.
- Create a bundler (CLI style for future CI) for do this task that bundle all the plugins that we want for our proyect, I tried this before to do this a achieve some pretty early results that use in our games, but as before the lack of time to work on this forced me to desist. (this is the repo https://github.com/kloder-games/godotisan)

So if you come closer with any of this approach (or a best way) tell us for point in this direction in the future.

**Comment by Shin-NiL** [comment]
I think that the GDNative approach is the best one for long term. I have no idea where to start though :(

**Comment by Applemann** [comment]
@Shin-NiL Maybe you can see the official documentation about GDNative: http://docs.godotengine.org/en/3.0/tutorials/plugins/gdnative/gdnative-c-example.html  for learn more about it..

Maybe you will only create [GDNLIB file](http://docs.godotengine.org/en/3.0/tutorials/plugins/gdnative/gdnative-c-example.html#creating-our-gdnlib-file) where will be information about our admob library and where is it for load in Android..

I hope that will be works..

**Comment by Shin-NiL** [comment]
I have no luck, even with the hello world example :(

**Comment by Shin-NiL** [comment]
Please check out [this repository](https://github.com/Shin-NiL/godot-custom-mobile-template) for templates using this module.
