### ISSUE TITLE
No load rewarded video 

### ISSUE THREAD

**Issue by KylaCpper** [kloder-games/godot-admob#71]
**OS target (Android/iOS):**
android

**Godot version:**
3.06

**Issue description:**

Both banner and interstitial can run
But the rewarded video can't load
I get the parameter in the _on_rewarded_video_ad_failed_to_load callback function is 3
Is this ERROR_CODE_NO_FILL?
isReal = false
adRewardedId = "ca-app-pub-3940256099942544/5224354917"

**Comment by Shin-NiL** [comment]
Please check the 'Troubleshooting' section on the REAME file.
