### ISSUE TITLE
Floating crash in iOS, GodotAdmob Module already initialized 

### ISSUE THREAD

**Issue by AndrewMayor** [kloder-games/godot-admob#72]
**OS target (Android/iOS):**
iOS

**Godot version:3.x**

**Issue description:**
Having this crash in xCode every once in a while. Sometimes game loads as expected, but sometimes it crashes. (`GodotAdmob Module already initialized`)
`At: modules/admob/ios/src/godotAdmob.mm:12:GodotAdmob() - Condition ' instance != __null ' is true.`

**Comment by AndrewMayor** [comment]
Problem was resolved with recompiling modules.

**Comment by AndrewMayor** [comment]
Sorry need reopen, Crash persists. When device is rebooted, on clean install or just running after reboot app will crash with 100% chance. Sometimes it will crash without reboot, once in 5-10 restarts of the app.

**Comment by JBacal** [comment]
Seeing similar issue on my iPhone.  If app has been in background for a period of time and then the App is reselected, it will crash as soon as Admob tries to (re)install.  Is it possible for the Admob module to check for a previous installation and then not try to reinstall Itself to avoid this crash?

**Comment by fogine** [comment]
Compiled against current masteer af9c58e, I see this crash 80% of time during app startup, if it doesnt crash for some reason, it seems to be stable then.
iOS 12.4.1

I can test whatever but I'm not apple developer, I've setup virtualized environment and got iphone device just to get my apps on iTunes....

**Comment by fogine** [comment]
@Shin-NiL , Why does `GodotAdmob` class has to be declared as singleton anyway?
(I'm not talking about `Engine::get_singleton()->add_singleton`)

I've eliminated the error by removing the singleton pattern, which most probably caused errors because of not being multi-treaded safe implementation.

Seems to be stable so far. I've `banner` & `interstitial` and `rewarded` ads working.

**Comment by JBacal** [comment]
@fogine  Could be specific about the code changes you made to remove the error?

**Comment by fogine** [comment]
@JBacal as you can see, github references my commit above my previous comment..
For clarity, you can see my changes here
https://github.com/fogine/godot-admob/commit/263c42550b9865f3dc9ed49078832777ca203ea0

**Comment by Shin-NiL** [comment]
> Why does GodotAdmob class has to be declared as singleton anyway?
(I'm not talking about Engine::get_singleton()->add_singleton)

@fogine, I don't remember, I think I was just following the same pattern I've found on another iOS module.

If it's working fine can you please create a pull request? Thank you ;)
