### ISSUE TITLE
"web thread mult. locks" crash after interstitial in iOS

### ISSUE THREAD

**Issue by AndrewMayor** [kloder-games/godot-admob#73]
**OS target (Android/iOS):iOS**

**Godot version:3.x**

**Issue description:**
Please help.
Using Banners and Interstitials in my game (No rewarded video), Crash on Interstitial close. I saw Known Issues section, but it is clear there that Rewarded Video have this probem not Interstitial.

2019-02-28 11:11:38.590528+0200 MyApp[1769:350590] Interstitial loaded
Interstitial loaded
2019-02-28 11:12:31.125165+0200 MyApp[1769:350590] showing
showing
2019-02-28 11:12:31.125244+0200 MyApp[1769:350590] Calling showInterstitial
2019-02-28 11:12:31.127545+0200 MyApp[1769:350590] interstitialWillPresentScreen
******** screen size 750, 1334
2019-02-28 11:12:37.600390+0200 MyApp[1769:350590] interstitialWillDismissScreen
******** screen size 750, 1334
2019-02-28 11:12:37.619491+0200 MyApp[1769:350748] void _WebThreadLock(), 0x10abb8040: Multiple locks on web thread not allowed! Please file a bug. Crashing now...

**Comment by Shin-NiL** [comment]
Maybe this bug occurs when more than one ad type is used, not only rewarded video. If somebody can do further tests will be great.

**Comment by fogine** [comment]
Compiled against current masteer af9c58e , I havent encountered this issue so far.
I'm using banner, interstitial and rewarded video ads at different stages of a game... not using them at once...

iOS 12.4.1
Godot 3.1.1

**Comment by fogine** [comment]
Well unfortunately I did manage to replicate this after closing interstitial ad...
I dont get why after closing `interstitial` / `rewarded` ads, the `banner` ad is explicitly enabled and showed...  
https://github.com/kloder-games/godot-admob/blob/master/admob/ios/src/AdmobRewarded.mm#L84

I'm not sure about this but it is probably the source of issues as after an interstitial is closed I call loadIntersitial which might not finish loading in time.  
Instead, implementation of proper ad loading & showing/hiding should be left on the end user.

**Comment by gustavottc** [comment]
This is a know issue #53 please close this issue
