### ISSUE TITLE
ads not show when change isreal value to true

### ISSUE THREAD

**Issue by SMaiLubis** [kloder-games/godot-admob#76]
**OS target (Android/iOS):**
android

**Godot version:**
2.1.5

**Issue description:**
i use my own ads id. My banner ads has "test ad" label when i try to load, and when i change `isreal=false` to `isreal=true` i get error `onAdFailedToLoad -> ERROR_CODE_NO_FILL` is it problem from admob?

**Comment by wombatwingdings** [comment]
Are you using Release build? I've had the same thing with Debug build, but works OK in Release.

**Comment by Shin-NiL** [comment]
Please check the README file, "Troubleshooting" section.

**Comment by SMaiLubis** [comment]
If you mean unchecked debugging enable, yes i already try it, and still get error code 3 if i set variable isreal = true
