### ISSUE TITLE
Request: Please provide builds

### ISSUE THREAD

**Issue by mydoghasworms** [kloder-games/godot-admob#8]
Please can you provide compiled binaries of the templates :pray:

**Comment by Shin-NiL** [comment]
[Here's the one](http://www.mediafire.com/file/ddomuou6j3za3vc/2.1.4-admob-share.apk) I'm using (release mode).

**Comment by mydoghasworms** [comment]
Thanks @Shin-NiL!

**Comment by phaitonican** [comment]
Here for Godot 3.0.6 Stable: [here](https://www.mediafire.com/file/b68y68mmsj1626i/APKs_for_Godot_v3.0.6.stable.tar.gz/file)

**Comment by Shin-NiL** [comment]
Please check out [this repository](https://github.com/Shin-NiL/godot-custom-mobile-template) for templates using this module.
