### ISSUE TITLE
Work on Godot 3.1?

### ISSUE THREAD

**Issue by Skynoryu** [kloder-games/godot-admob#81]
I compiled the modules and implemented everything correctly but did not work on GODOT 3.1.

Has anyone succeeded or is the module not optimized for this version of the engine?

**Comment by Shin-NiL** [comment]
For Android it's working fine. For iOS I can't tell you.

**Comment by Skynoryu** [comment]
@Shin-NiL , agora vi que você é do Brasil.

Continuo obtendo o mesmo erro.
Recompilei os módulos para tirar qualquer possibilidade de que fosse como o ocorrido aqui
https://github.com/godotengine/godot/issues/21630#issuecomment-417759289

E obtive esse logcat
--------- beginning of system
04-23 16:55:59.042 24440 24440 I godot   : **INIT EVENT! - 0xed5d4360
04-23 16:55:59.043 24440 24440 I godot   : ***************** HELLO FROM JNI!!!!!!!!
04-23 16:55:59.043 24440 24440 I godot   : *******CLASS FOUND!!!
04-23 16:55:59.043 24440 24440 I godot   : STEP2, 0x2116
04-23 16:55:59.043 24440 24440 I godot   : STEP3 -287103596
04-23 16:55:59.043 24440 24440 I godot   : STEP4, 0x79
04-23 16:55:59.043 24440 24440 I godot   : STEP4.5, 0x2126
04-23 16:55:59.043 24440 24440 I godot   : STEP7
04-23 16:55:59.043 24440 24440 I godot   : STEP8
04-23 16:55:59.043 24440 24440 I godot   : *******GOT METHOD _dir_open ok!!
04-23 16:55:59.043 24440 24440 I godot   : *******GOT METHOD _dir_next ok!!
04-23 16:55:59.043 24440 24440 I godot   : *******GOT METHOD _dir_close ok!!
04-23 16:55:59.043 24440 24440 I godot   : *******GOT METHOD _dir_is_dir ok!!
04-23 16:55:59.043 24440 24440 I godot   : starting to attempt get methods
04-23 16:55:59.043 24440 24440 I godot   : *******GOT METHOD _init_audio ok!!
04-23 16:55:59.043 24440 24440 I godot   : *******GOT METHOD _write_buffer ok!!
04-23 16:55:59.043 24440 24440 I godot   : *******GOT METHOD _quit ok!!
04-23 16:55:59.043 24440 24440 I godot   : *******GOT METHOD _pause ok!!
04-23 16:55:59.043 24440 24440 I godot   : test construction 5
04-23 16:55:59.043 24440 24440 I godot   : running from dir /
04-23 16:55:59.136 24440 24477 I godot   : **SETUP
04-23 16:55:59.136 24440 24477 I godot   : CMDLINE LEN 0 - APK EXPANSION 0
04-23 16:55:59.165 24440 24477 I godot   : *****SETUP OK
04-23 16:55:59.165 24440 24477 I godot   : ANDROID MODULES : org/godotengine/godot/GodotAdMob
04-23 16:55:59.165 24440 24477 I godot   : mod count: 1
04-23 16:55:59.165 24440 24477 I godot   : LOADING MODULE: org/godotengine/godot/GodotAdMob
04-23 16:55:59.166 24440 24477 I godot   : ****^*^*?^*^*class data 139
04-23 16:55:59.198 24440 24477 I godot   : ****^*^*?^*^*class instance 145
04-23 16:55:59.275 24440 24477 I godot   : ^_^_^_^_^ newcontext 0
04-23 16:55:59.275 24440 24477 I godot   : ^_^_^_^_^ resize 0, 1080, 1920
04-23 16:55:59.275 24440 24477 I godot   : **FIRST_STEP
04-23 16:55:59.277 24440 24440 I godot   : WARNING: not found: display/driver/keep_screen_on
04-23 16:55:59.285 24440 24477 I godot   : OpenGL ES 3.0 Renderer: Mali-T830
04-23 16:55:59.332 24440 24477 I godot   : OpenSL Init OK!
04-23 16:55:59.353 24440 24477 I godot   : Boot splash path: res://sprites/gui/bg.png
04-23 16:55:59.846 24440 24477 E godot   : **ERROR**: Bytecode is too New! Please use a newer engine version.
04-23 16:55:59.846 24440 24477 E godot   :    At: modules/gdscript/gdscript_tokenizer.cpp:1142:set_code_buffer() - Condition ' version > 12 ' is true. returned: ERR_INVALID_DATA
04-23 16:55:59.846 24440 24477 E godot   : **ERROR**: FATAL: Index p_index=-1 out of size (size()=0)
04-23 16:55:59.846 24440 24477 E godot   :    At: core/vector.h:147:operator[]() - FATAL: Index p_index=-1 out of size (size()=0)

Se puder dar uma ajuda, ficarei ainda mais grato,

**Comment by Shin-NiL** [comment]
Pela mensagem de erro parece que você está usando uma versão da template diferente da usada no editor. Se estiver usa do a versão 3.1.0 pra fazer o seu jogo, tente usar minha template pré compilada https://github.com/Shin-NiL/godot-custom-mobile-template

**Comment by bubudge** [comment]
I wasn't able to use this module on Godot 3.1. In my case I removed 'NDK_TARGET' from my PC and it worked well.

**Comment by siherrmann** [comment]
I try to use this module at the moment but either my game keeps crashing or the close function won't work. If I build only two scenes, first one with an interstitial ad and then one with some buttons and use the function _on_interstitial_closed() to change the scene, the ad closes for a moment and comes right back without changing the scene. I would really appreciate your help.

**Comment by Shin-NiL** [comment]
@siherrmann 
Does the example project work for you?
Please open a new issue and post your sample code if possible.
