### ISSUE TITLE
on_interstitial_loaded not firing

### ISSUE THREAD

**Issue by DejaVuLoop** [kloder-games/godot-admob#83]
**OS target: Android**

**Godot version: 3.1-stable**

**Issue description:**
I've been able to load an ad with a valid unit id and show it if I tell godot to wait seven seconds between the two actions. If I instead try to handle this by using the `on_interstitial_loaded()` callback, the program waits indefinitely. I've tried the following approaches to prove that the issues lies with the callback:
```gdscript
func _ready():
	var ad = Engine.get_singleton("AdMob")
	ad.init(false, get_instance_id())
	ad.loadInterstitial(UNIT_ID)

func on_interstitial_loaded():
	# cue visual feedback

func on_interstitial_not_loaded():
	# cue more visual feedback
```
No visual feedback from either callback. Same with below:
```gdscript
func _ready():
	var ad = Engine.get_singleton("AdMob")
	ad.init(false, get_instance_id())
	ad.loadInterstitial(UNIT_ID)
	yield(self, "on_interstitial_loaded")
	# cue visual feedback
```

It's entirely possible I'm doing this completely wrong, but after staring at the example code for a while, I can't see any real functional differences.

**Comment by Shin-NiL** [comment]
Please check the callback names, it should start with an underscore ```_on_interstitial_loaded()```. The name must be the exact same as in the README. For more details, see the demo code.

**Comment by DejaVuLoop** [comment]
That fixed it, sorry and thank you!
