### ISSUE TITLE
Closing interstitial ad doesn't work

### ISSUE THREAD

**Issue by siherrmann** [kloder-games/godot-admob#84]
OS target (Android/iOS): Android
Godot version: 3.1

I have a scene with an interstitial ad, the example project does work, the interstitial ad in my own scene does load too so the module is alright. I use the function `_on_interstitial_close()` to change the scene. But when I try to close the ad, the ad seems to close but comes right back and the scene doesn't change. I added the else statement in the ready function to check if the scene loads on my PC where I didn't set up the AdMob module and yes, the scene has no errors and does load.

```
extends Node2D

var admob = null
var isReal = false
var isTop = true
var adInterstitialId = "ca-app-pub-3940256099942544/1033173712" # google test ad ID

func _ready():
	print(Engine.get_singleton("AdMob"))
	if(Engine.has_singleton("AdMob")):
		admob = Engine.get_singleton("AdMob")
		admob.init(isReal, get_instance_id())
	else:
		get_tree().change_scene("res://Scenes/Start.tscn")
	
	get_tree().connect("screen_resized", self, "onResize")
	
	if admob != null:
		admob.loadInterstitial(adInterstitialId)

func _on_admob_network_error():
	print("Network Error")

func _on_interstitial_not_loaded():
	print("Error: Interstitial not loaded")
	get_tree().change_scene("res://Scenes/Start.tscn")

func _on_interstitial_loaded():
	print("Interstitial loaded")
	if admob != null:
		admob.showInterstitial()

func _on_interstitial_close():
	get_tree().change_scene("res://Scenes/Start.tscn")
	print("Interstitial closed")

func onResize():
	if admob != null:
		admob.resize()
```

**Comment by Shin-NiL** [comment]
Well, I'm using the demo project, just added a new empty scene and call ```get_tree().change_scene("res://scene2.tscn")``` inside the ```_on_interstitial_close```, no issue here.

One thing you can try to do is await for some frames update before changing the scene:
```
func _on_interstitial_close():
	yield(get_tree(), "idle_frame")
        yield(get_tree(), "idle_frame")
	get_tree().change_scene("res://Scenes/Start.tscn")
	print("Interstitial closed")
```

Are you 'reloading' the same scene? Does your 'Start.tscn' scene load the ads too?

**Comment by siherrmann** [comment]
Thank you for your fast answer.

That's interesting. My 'Start.tscn' doesn't load with the ads. When I put the AdMob code into the script of the start scene and set the 'Start.tscn' as start scene, the game doesn't even start, just the Godot splash screen shows up, flickers and then the game crashes.

This is how I put the AdMob code into the script of 'Start.tscn':

```
extends Node2D

var admob = null
var isReal = false
var isTop = true
var adInterstitialId = "ca-app-pub-3940256099942544/1033173712" # google test ad ID

var saveDataFile = File.new()
var savePath = "user://savegame.save"
var saveData = {"highscores": [0,0,0,0,0], "highscoresEasy": [0,0,0,0,0], "easyMode": false}

onready var startAnimation = get_node("Container/StartAnimation")
onready var easyButton = get_node("EasyButton")
onready var highscores = get_node("Highscores")

var gameStarted = false

func _ready():
	if(Engine.has_singleton("AdMob")):
		admob = Engine.get_singleton("AdMob")
		admob.init(isReal, get_instance_id())
	
	if admob != null:
		admob.loadInterstitial(adInterstitialId)
	
	randomize()
	
	if not saveDataFile.file_exists(savePath):
		saveDataFile.open_encrypted_with_pass(savePath, File.WRITE, "slidingCat")
		saveDataFile.store_var(saveData)
		saveDataFile.close()
		
	saveDataFile.open_encrypted_with_pass(savePath, File.READ, "slidingCat")
	saveData = saveDataFile.get_var()
	saveDataFile.close()
	
	Global.easymode = saveData["easyMode"]
	
	if Global.easymode:
		easyButton.set_text("Easy mode: ON")
	elif !Global.easymode:
		easyButton.set_text("Easy mode: OFF")

func _on_interstitial_loaded():
	print("Interstitial loaded")
	if admob != null:
		admob.showInterstitial()

func _on_interstitial_close():
	yield(get_tree(), "idle_frame")
	yield(get_tree(), "idle_frame")
	get_tree().change_scene("res://Scenes/Start.tscn")
	print("Interstitial closed")
```

**Comment by Shin-NiL** [comment]
Can you reproduce the issue on a sample project? If so, post the zip here, this way it will be easier to me to debug it.

**Comment by siherrmann** [comment]
I actually made already more than one sample projects to check different variants.
[TestAdmobScene.zip](https://github.com/kloder-games/godot-admob/files/3204646/TestAdmobScene.zip)

**Comment by Shin-NiL** [comment]
Tested your project. No crash here, what's happening is:

Start scene show interstitial -> close interstitial -> open blank scene -> show interstitial -> close interstitial -> open start scene and so on.

I don't know if this loop is intentional, but as you're loading and showing the ads in every scene that's loaded, that's the expected behavior. For every time you're loading a scene a new interstitial is loaded and shown.

One thing you must be aware is that the ads acts like a general overlay above your app, so they don't respect the godot lifecycle. One good strategy to manage the ads is adding all their logic on a global autoload (singleton) script, this way there will be only one instance to care about.

**Comment by siherrmann** [comment]
Did you test it on an android device? On windows, it runs just fine, but on my smartphone, it does not. And no, the loop wasn't intentional, I didn't recognize this loop because on windows I didn't add the AdMob module and on the smartphone, the game just crashed. ;)

Could you test it on an android device?

**Comment by Shin-NiL** [comment]
I have tested on my real Android device only.

Did you compile the templates by yourself? If so could you test with my [precompiled ones](https://github.com/Shin-NiL/godot-custom-mobile-template)? In any case make sure you're matching the exact same version of your editor and the template. If you are using Godot 3.1.0 on the editor you must compile the template for Godot 3.1.0 for Android also not the master.

**Comment by siherrmann** [comment]
Yes, I did use your templates, when I try to compile my own (for the Godot master -> Godot 3.2dev) an error occurs.

**Comment by siherrmann** [comment]
My smartphone has only 2gb of RAM, could that be a limiting factor? 1gb is used up by my normal stuff, the AdMob scene alone uses around 300mb of RAM, but my scene is not that big that it uses up the rest of the memory or could it be?

**Comment by Shin-NiL** [comment]
I don't think so, my phone has 2gb of RAM also.

**Comment by siherrmann** [comment]
What version of python, java (ndk/jdk), android studio and Gradle do you use? Could it be a problem that I use OpenJDK?

**Comment by Shin-NiL** [comment]
To run on emulator you should include the x86 CPU architecture.

I'm running openjdk version 1.8.0_191, ndk r17b, python 2.7.12, but I don't think it's the problem, once you also used my precompiled templates.

**Comment by siherrmann** [comment]
Mmh, do you have precompiled templates for Windows? So I can test it there too?

**Comment by Shin-NiL** [comment]
The Admob module doesn't support windows.

**Comment by siherrmann** [comment]
Oh... ;) How can I find out, what's the error? When I use the Godot debug mode, no error shows up.

**Comment by Shin-NiL** [comment]
Does everything work fine using the debug template? If so we've already saw a [similar issue](https://github.com/Shin-NiL/godot-custom-mobile-template/issues/3). Could you try to make a new test without the admob module, using the official android template?

**Comment by siherrmann** [comment]
Without the AdMob module it works fine on my phone. It just shows the Start.tscn scene. The Debug template is used, when I use the Debug mode of Godot and the release template is used when I export it without Debug features activated, is that right? If so, I already used the official Debug template as well as the official Release template.

**Comment by Shin-NiL** [comment]
I have tested your project with both, release and debug and all of them worked fine. I'm sorry but I have no idea what could be happening.

**Comment by siherrmann** [comment]
Ok, I think I'll try the export with your templates on Linux until now I have worked with windows but probably Linux gives a better result, how knows. Thanks for your help, I will send an update if it worked or not.

**Comment by siherrmann** [comment]
Now I tried to build export templates in Linux, without the AdMob module the build is successful but when I add the AdMob module this error occurs:
![image](https://user-images.githubusercontent.com/25087590/58568310-548dcc00-8234-11e9-86a4-fabc159d3e4f.png)
When I remember correctly the same error occurred in windows. Could that error be part of the export failure?

**Comment by Shin-NiL** [comment]
I don't know if the module will work on master, I'm working with 3.1.1, the latest Godot stable version.

**Comment by siherrmann** [comment]
Yes, on 3.1 it works. Thank you very much, I just exported the game in Ubuntu and it works with the AdMob module. I still don't know why it didn't work in Windows, but now I'm just using Ubuntu.

**Comment by Shin-NiL** [comment]
Nice! Yeah, I think this issue could be closed now.
