### ISSUE TITLE
where is the hook between the functions exposed in gdscript and the native client code talking to admob? 

### ISSUE THREAD

**Issue by davidholiday** [kloder-games/godot-admob#85]
first - thank you for doing this and for making it open source! I'm learning godot and curious as to where the hook is between the android java admob code and the functions that are exposed to gdscript. for example, `_on_admob_ad_loaded()` is exposed to gdscript. how is that method hooked into the java client code? 

ty!

**Comment by Shin-NiL** [comment]
For the callbacks, it's using GodotLib.calldeferred as you can see [here](https://github.com/kloder-games/godot-admob/blob/5c69c9cf1e213d633e862ac5830887e3902cda6a/admob/android/GodotAdMob.java#L241). The another ones are exposed at [registerClass](https://github.com/kloder-games/godot-admob/blob/5c69c9cf1e213d633e862ac5830887e3902cda6a/admob/android/GodotAdMob.java#L512).

**Comment by davidholiday** [comment]
awesomeness - ty!
