### ISSUE TITLE
It isn't working with real ads

### ISSUE THREAD

**Issue by jshlw** [kloder-games/godot-admob#86]
I tried interstitial ads and it shows the follow:
"Interstitial not loaded"

But when it's not real ads, it works very well.

**Comment by Shin-NiL** [comment]
Please fill the issue template, this way it's easier to us to try to help you.

**OS target (Android/iOS):**


**Godot version:**


**Issue description:**

**Comment by jshlw** [comment]
OS target (Android/iOS): Android

Godot version: 3.1.1

Issue description: Only test ads are working. When I try to change to real ads (interstitial for example), I receive "Interstitial not loaded" and nothing happens.

**Comment by jshlw** [comment]
I guess it is happening because I'm using `get_instance_id()` instead `OS.get_unique_id()`. I don't know what the Godot 3 example was refering to.

**Comment by Shin-NiL** [comment]
Could you try to debug using adb as stated in the readme? It take some time to a real ad to load, maybe you're trying to show a interstitial before it is loaded.

**Comment by jshlw** [comment]
My AdMob ad blocks received almost 500 requests. I read about it and I'm waiting some time before doing anything.

**Comment by phaitonican** [comment]
Do you see the error code? If it's a 3 then it means that AdMob doesn't have an Ad to provide currently, mostly if the ad is set up recently.

**Comment by takhimi** [comment]
@jshlw any updates on this? Do you managed to solve it?

**Comment by jshlw** [comment]
@takhimi it isn't working yet.

**Comment by phaitonican** [comment]
@jshlw, what's the error code if any?

**Comment by jshlw** [comment]
Now it's working! I don't know exactly why but it works well.
