### ISSUE TITLE
Where to put the id app?

### ISSUE THREAD

**Issue by HerculesMendes** [kloder-games/godot-admob#88]
**OS target (Android/iOS):**Android

**Godot version:**3.0.6

**Issue description:**I know where to put the ad block id, but where do I put the id of the app that admob provides

I was trying to put real ads and put the ad unit ID, but I'm not sure where to put the app ID, I did not export the app, but I was wondering if it works without the id or where should I put this. English is not my native language, I hope you have understood, if yes, I hope you will help me.

**Comment by Shin-NiL** [comment]
If you are using Google Mobile Ads SDK <= 7.41.0 you don't need to use the app ID. If not, this module won't work until somebody update it, sorry.
