### ISSUE TITLE
Where to put the app ID that admob provide us.

### ISSUE THREAD

**Issue by ANOONBP** [kloder-games/godot-admob#95]
OS target (Android/iOS): Android
Godot version: 3.1.1
Issue description:

![image](https://user-images.githubusercontent.com/13798737/60680919-5e4fc280-9eb7-11e9-9f3b-ae1d8e4790e0.png)

**Comment by Shin-NiL** [comment]
You won't use the app-id in this module in this current version.

**Comment by ANOONBP** [comment]
So If I don't use app-id, The real ads should still work right ?

**Comment by Shin-NiL** [comment]
Yeah, it should work fine. This module uses play-services-ads:16.0.0 which doesn't require the app-id.

**Comment by ANOONBP** [comment]
Please tell me what did i just missed.
First thing first I tried test ads and it work properly. So I replace test ads id with real ads id that I created 2 days ago then I generate keystore for release and use it on export section. Then unchecked export with debug.

FYI: I using your android_release.apk

**Comment by Shin-NiL** [comment]
You should debug using ```adb logcat``` as described in the readme file. This way we can try to help you any further.

**Comment by ANOONBP** [comment]
![image](https://user-images.githubusercontent.com/13798737/60684256-c659d500-9ec6-11e9-957b-b658d2d68063.png)

Here you go.

**Comment by Shin-NiL** [comment]
Well, you're getting the error code 0 from Admob servers, you can try google that to find more information. The [official documentation](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#ERROR_CODE_INTERNAL_ERROR) describe this code like this:

> Something happened internally; for instance, an invalid response was received from the ad server.

**Comment by ANOONBP** [comment]
Thank for the help.

It return 0 because I didn't setup payment method and now It return error code 3 instead. According to google doc maybe because my app didn't release yet and the request rate is very low so no ADS for now.
